// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pb/ycj.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ycj_BetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSN       *string                `protobuf:"bytes,1,opt,name=orderSN,proto3,oneof" json:"orderSN,omitempty"`             // 订单号
	Balance       *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`           // 玩家当前余额
	BetAmount     *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`       // 本局下注金额
	CurrentWin    *float64               `protobuf:"fixed64,4,opt,name=currentWin,proto3,oneof" json:"currentWin,omitempty"`     // 本局赢取金额
	FreeWin       *float64               `protobuf:"fixed64,5,opt,name=freeWin,proto3,oneof" json:"freeWin,omitempty"`           // 免费游戏累计赢取
	TotalWin      *float64               `protobuf:"fixed64,6,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`         // 本回合总赢取
	Free          *bool                  `protobuf:"varint,7,opt,name=free,proto3,oneof" json:"free,omitempty"`                  // 是否处于免费模式
	Review        *int64                 `protobuf:"varint,8,opt,name=review,proto3,oneof" json:"review,omitempty"`              // 复盘标志
	WinInfo       *Ycj_WinInfo           `protobuf:"bytes,9,opt,name=winInfo,proto3,oneof" json:"winInfo,omitempty"`             // 中奖详情
	Cards         []int64                `protobuf:"varint,10,rep,packed,name=cards,proto3" json:"cards,omitempty"`              // 符号网格 1x3，共3个元素
	Multiplier    *float64               `protobuf:"fixed64,11,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"`    // 返奖倍数
	IsRoundOver   *bool                  `protobuf:"varint,12,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver,omitempty"`   // 是否本局结束
	State         *int64                 `protobuf:"varint,13,opt,name=state,proto3,oneof" json:"state,omitempty"`               // 游戏状态 1=普通 2=免费
	FreeNum       *int64                 `protobuf:"varint,14,opt,name=freeNum,proto3,oneof" json:"freeNum,omitempty"`           // 剩余免费次数
	FreeTime      *int64                 `protobuf:"varint,15,opt,name=freeTime,proto3,oneof" json:"freeTime,omitempty"`         // 已使用免费次数
	WinGrid       []int64                `protobuf:"varint,16,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`          // 中奖位置网格 1x3
	IsGameOver    *bool                  `protobuf:"varint,17,opt,name=isGameOver,proto3,oneof" json:"isGameOver,omitempty"`     // 大回合结束
	Next          *bool                  `protobuf:"varint,18,opt,name=next,proto3,oneof" json:"next,omitempty"`                 // 是否需要继续请求（推展/重转）
	IsExtendMode  *bool                  `protobuf:"varint,19,opt,name=isExtendMode,proto3,oneof" json:"isExtendMode,omitempty"` // 是否在推展模式中
	IsRespinMode  *bool                  `protobuf:"varint,20,opt,name=isRespinMode,proto3,oneof" json:"isRespinMode,omitempty"` // 是否在重转模式中
	AddFreeNum    *int64                 `protobuf:"varint,21,opt,name=addFreeNum,proto3,oneof" json:"addFreeNum,omitempty"`     // 本局增加的免费次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ycj_BetOrderResponse) Reset() {
	*x = Ycj_BetOrderResponse{}
	mi := &file_pb_ycj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ycj_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ycj_BetOrderResponse) ProtoMessage() {}

func (x *Ycj_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ycj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ycj_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Ycj_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_ycj_proto_rawDescGZIP(), []int{0}
}

func (x *Ycj_BetOrderResponse) GetOrderSN() string {
	if x != nil && x.OrderSN != nil {
		return *x.OrderSN
	}
	return ""
}

func (x *Ycj_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil && x.CurrentWin != nil {
		return *x.CurrentWin
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetFree() bool {
	if x != nil && x.Free != nil {
		return *x.Free
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetWinInfo() *Ycj_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Ycj_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Ycj_BetOrderResponse) GetMultiplier() float64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Ycj_BetOrderResponse) GetIsGameOver() bool {
	if x != nil && x.IsGameOver != nil {
		return *x.IsGameOver
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetNext() bool {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetIsExtendMode() bool {
	if x != nil && x.IsExtendMode != nil {
		return *x.IsExtendMode
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetIsRespinMode() bool {
	if x != nil && x.IsRespinMode != nil {
		return *x.IsRespinMode
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetAddFreeNum() int64 {
	if x != nil && x.AddFreeNum != nil {
		return *x.AddFreeNum
	}
	return 0
}

// Ycj_WinInfo 中奖详情
type Ycj_WinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftSymbol    *int64                 `protobuf:"varint,1,opt,name=leftSymbol,proto3,oneof" json:"leftSymbol,omitempty"`   // 左侧数字符号
	MidSymbol     *int64                 `protobuf:"varint,2,opt,name=midSymbol,proto3,oneof" json:"midSymbol,omitempty"`     // 中间特殊符号
	RightSymbol   *int64                 `protobuf:"varint,3,opt,name=rightSymbol,proto3,oneof" json:"rightSymbol,omitempty"` // 右侧数字符号
	Multiplier    *float64               `protobuf:"fixed64,4,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"`  // 返奖倍数
	IsExtend      *bool                  `protobuf:"varint,5,opt,name=isExtend,proto3,oneof" json:"isExtend,omitempty"`       // 是否触发推展
	IsRespin      *bool                  `protobuf:"varint,6,opt,name=isRespin,proto3,oneof" json:"isRespin,omitempty"`       // 是否触发重转
	IsFree        *bool                  `protobuf:"varint,7,opt,name=isFree,proto3,oneof" json:"isFree,omitempty"`           // 是否触发夺宝
	FreeSpinNum   *int64                 `protobuf:"varint,8,opt,name=freeSpinNum,proto3,oneof" json:"freeSpinNum,omitempty"` // 免费次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ycj_WinInfo) Reset() {
	*x = Ycj_WinInfo{}
	mi := &file_pb_ycj_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ycj_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ycj_WinInfo) ProtoMessage() {}

func (x *Ycj_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_ycj_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ycj_WinInfo.ProtoReflect.Descriptor instead.
func (*Ycj_WinInfo) Descriptor() ([]byte, []int) {
	return file_pb_ycj_proto_rawDescGZIP(), []int{1}
}

func (x *Ycj_WinInfo) GetLeftSymbol() int64 {
	if x != nil && x.LeftSymbol != nil {
		return *x.LeftSymbol
	}
	return 0
}

func (x *Ycj_WinInfo) GetMidSymbol() int64 {
	if x != nil && x.MidSymbol != nil {
		return *x.MidSymbol
	}
	return 0
}

func (x *Ycj_WinInfo) GetRightSymbol() int64 {
	if x != nil && x.RightSymbol != nil {
		return *x.RightSymbol
	}
	return 0
}

func (x *Ycj_WinInfo) GetMultiplier() float64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Ycj_WinInfo) GetIsExtend() bool {
	if x != nil && x.IsExtend != nil {
		return *x.IsExtend
	}
	return false
}

func (x *Ycj_WinInfo) GetIsRespin() bool {
	if x != nil && x.IsRespin != nil {
		return *x.IsRespin
	}
	return false
}

func (x *Ycj_WinInfo) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Ycj_WinInfo) GetFreeSpinNum() int64 {
	if x != nil && x.FreeSpinNum != nil {
		return *x.FreeSpinNum
	}
	return 0
}

var File_pb_ycj_proto protoreflect.FileDescriptor

const file_pb_ycj_proto_rawDesc = "" +
	"\n" +
	"\fpb/ycj.proto\x12\x03ycj\"\xc8\a\n" +
	"\x14Ycj_BetOrderResponse\x12\x1d\n" +
	"\aorderSN\x18\x01 \x01(\tH\x00R\aorderSN\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01H\x03R\n" +
	"currentWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\x05 \x01(\x01H\x04R\afreeWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\x06 \x01(\x01H\x05R\btotalWin\x88\x01\x01\x12\x17\n" +
	"\x04free\x18\a \x01(\bH\x06R\x04free\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\b \x01(\x03H\aR\x06review\x88\x01\x01\x12/\n" +
	"\awinInfo\x18\t \x01(\v2\x10.ycj.Ycj_WinInfoH\bR\awinInfo\x88\x01\x01\x12\x14\n" +
	"\x05cards\x18\n" +
	" \x03(\x03R\x05cards\x12#\n" +
	"\n" +
	"multiplier\x18\v \x01(\x01H\tR\n" +
	"multiplier\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\f \x01(\bH\n" +
	"R\visRoundOver\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\r \x01(\x03H\vR\x05state\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\x0e \x01(\x03H\fR\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\x0f \x01(\x03H\rR\bfreeTime\x88\x01\x01\x12\x18\n" +
	"\awinGrid\x18\x10 \x03(\x03R\awinGrid\x12#\n" +
	"\n" +
	"isGameOver\x18\x11 \x01(\bH\x0eR\n" +
	"isGameOver\x88\x01\x01\x12\x17\n" +
	"\x04next\x18\x12 \x01(\bH\x0fR\x04next\x88\x01\x01\x12'\n" +
	"\fisExtendMode\x18\x13 \x01(\bH\x10R\fisExtendMode\x88\x01\x01\x12'\n" +
	"\fisRespinMode\x18\x14 \x01(\bH\x11R\fisRespinMode\x88\x01\x01\x12#\n" +
	"\n" +
	"addFreeNum\x18\x15 \x01(\x03H\x12R\n" +
	"addFreeNum\x88\x01\x01B\n" +
	"\n" +
	"\b_orderSNB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_currentWinB\n" +
	"\n" +
	"\b_freeWinB\v\n" +
	"\t_totalWinB\a\n" +
	"\x05_freeB\t\n" +
	"\a_reviewB\n" +
	"\n" +
	"\b_winInfoB\r\n" +
	"\v_multiplierB\x0e\n" +
	"\f_isRoundOverB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\r\n" +
	"\v_isGameOverB\a\n" +
	"\x05_nextB\x0f\n" +
	"\r_isExtendModeB\x0f\n" +
	"\r_isRespinModeB\r\n" +
	"\v_addFreeNum\"\x98\x03\n" +
	"\vYcj_WinInfo\x12#\n" +
	"\n" +
	"leftSymbol\x18\x01 \x01(\x03H\x00R\n" +
	"leftSymbol\x88\x01\x01\x12!\n" +
	"\tmidSymbol\x18\x02 \x01(\x03H\x01R\tmidSymbol\x88\x01\x01\x12%\n" +
	"\vrightSymbol\x18\x03 \x01(\x03H\x02R\vrightSymbol\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x01H\x03R\n" +
	"multiplier\x88\x01\x01\x12\x1f\n" +
	"\bisExtend\x18\x05 \x01(\bH\x04R\bisExtend\x88\x01\x01\x12\x1f\n" +
	"\bisRespin\x18\x06 \x01(\bH\x05R\bisRespin\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\a \x01(\bH\x06R\x06isFree\x88\x01\x01\x12%\n" +
	"\vfreeSpinNum\x18\b \x01(\x03H\aR\vfreeSpinNum\x88\x01\x01B\r\n" +
	"\v_leftSymbolB\f\n" +
	"\n" +
	"_midSymbolB\x0e\n" +
	"\f_rightSymbolB\r\n" +
	"\v_multiplierB\v\n" +
	"\t_isExtendB\v\n" +
	"\t_isRespinB\t\n" +
	"\a_isFreeB\x0e\n" +
	"\f_freeSpinNumB\x18Z\x16egame-grpc/game/ycj/pbb\x06proto3"

var (
	file_pb_ycj_proto_rawDescOnce sync.Once
	file_pb_ycj_proto_rawDescData []byte
)

func file_pb_ycj_proto_rawDescGZIP() []byte {
	file_pb_ycj_proto_rawDescOnce.Do(func() {
		file_pb_ycj_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_ycj_proto_rawDesc), len(file_pb_ycj_proto_rawDesc)))
	})
	return file_pb_ycj_proto_rawDescData
}

var file_pb_ycj_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_ycj_proto_goTypes = []any{
	(*Ycj_BetOrderResponse)(nil), // 0: ycj.Ycj_BetOrderResponse
	(*Ycj_WinInfo)(nil),          // 1: ycj.Ycj_WinInfo
}
var file_pb_ycj_proto_depIdxs = []int32{
	1, // 0: ycj.Ycj_BetOrderResponse.winInfo:type_name -> ycj.Ycj_WinInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_ycj_proto_init() }
func file_pb_ycj_proto_init() {
	if File_pb_ycj_proto != nil {
		return
	}
	file_pb_ycj_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_ycj_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_ycj_proto_rawDesc), len(file_pb_ycj_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_ycj_proto_goTypes,
		DependencyIndexes: file_pb_ycj_proto_depIdxs,
		MessageInfos:      file_pb_ycj_proto_msgTypes,
	}.Build()
	File_pb_ycj_proto = out.File
	file_pb_ycj_proto_goTypes = nil
	file_pb_ycj_proto_depIdxs = nil
}
