// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pb/yhwy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// yhwy_BetOrderResponse 是单次下注返回给前端的完整结果。
type Yhwy_BetOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderSN        *string                `protobuf:"bytes,1,opt,name=orderSN,proto3,oneof" json:"orderSN,omitempty"`                 // 订单号
	Balance        *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`               // 当前余额
	BetAmount      *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`           // 本轮投注额
	CurrentWin     *float64               `protobuf:"fixed64,4,opt,name=currentWin,proto3,oneof" json:"currentWin,omitempty"`         // 本次 step 赢得金额
	FreeWin        *float64               `protobuf:"fixed64,5,opt,name=freeWin,proto3,oneof" json:"freeWin,omitempty"`               // 当前免费阶段累计赢得金额
	TotalWin       *float64               `protobuf:"fixed64,6,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`             // 本大回合累计赢得金额
	Free           *bool                  `protobuf:"varint,7,opt,name=free,proto3,oneof" json:"free,omitempty"`                      // 当前是否处于免费游戏
	Review         *int64                 `protobuf:"varint,8,opt,name=review,proto3,oneof" json:"review,omitempty"`                  // 复盘标记
	WinInfo        *Yhwy_WinInfo          `protobuf:"bytes,9,opt,name=winInfo,proto3,oneof" json:"winInfo,omitempty"`                 // 中奖详情
	Cards          []int64                `protobuf:"varint,10,rep,packed,name=cards,proto3" json:"cards,omitempty"`                  // 原始停轮盘面，按行展开的 20 个格子
	ScatterCount   *int64                 `protobuf:"varint,11,opt,name=scatterCount,proto3,oneof" json:"scatterCount,omitempty"`     // 最终盘面 Scatter 数量
	IsRoundOver    *bool                  `protobuf:"varint,12,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver,omitempty"`       // 当前 round 是否结束
	State          *int64                 `protobuf:"varint,13,opt,name=state,proto3,oneof" json:"state,omitempty"`                   // 当前阶段：1=Base, 21=Free
	FreeNum        *int64                 `protobuf:"varint,14,opt,name=freeNum,proto3,oneof" json:"freeNum,omitempty"`               // 剩余免费次数
	FreeTime       *int64                 `protobuf:"varint,15,opt,name=freeTime,proto3,oneof" json:"freeTime,omitempty"`             // 已执行免费次数
	WinGrid        []int64                `protobuf:"varint,16,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`              // 中奖位置掩码盘面，按行展开
	IsGameOver     *bool                  `protobuf:"varint,17,opt,name=isGameOver,proto3,oneof" json:"isGameOver,omitempty"`         // 整个免费大回合是否结束
	EffectCards    []int64                `protobuf:"varint,18,rep,packed,name=effectCards,proto3" json:"effectCards,omitempty"`      // 复位/扩散后、揭示前盘面
	FinalCards     []int64                `protobuf:"varint,19,rep,packed,name=finalCards,proto3" json:"finalCards,omitempty"`        // 揭示完成后的最终判奖盘面
	RevealSymbol   *int64                 `protobuf:"varint,20,opt,name=revealSymbol,proto3,oneof" json:"revealSymbol,omitempty"`     // 百变樱花本次揭示出的目标符号
	SpreadToReel   *int64                 `protobuf:"varint,21,opt,name=spreadToReel,proto3,oneof" json:"spreadToReel,omitempty"`     // 樱花扩散最远到第几列
	IsSakuraReset  *bool                  `protobuf:"varint,22,opt,name=isSakuraReset,proto3,oneof" json:"isSakuraReset,omitempty"`   // 是否触发樱花复位
	ResetDirection *int64                 `protobuf:"varint,23,opt,name=resetDirection,proto3,oneof" json:"resetDirection,omitempty"` // 复位方向：0=无,1=上移,2=下移
	LineMultiplier *int64                 `protobuf:"varint,24,opt,name=lineMultiplier,proto3,oneof" json:"lineMultiplier,omitempty"` // 所有中奖线赔率之和
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Yhwy_BetOrderResponse) Reset() {
	*x = Yhwy_BetOrderResponse{}
	mi := &file_pb_yhwy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_BetOrderResponse) ProtoMessage() {}

func (x *Yhwy_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_yhwy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Yhwy_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_pb_yhwy_proto_rawDescGZIP(), []int{0}
}

func (x *Yhwy_BetOrderResponse) GetOrderSN() string {
	if x != nil && x.OrderSN != nil {
		return *x.OrderSN
	}
	return ""
}

func (x *Yhwy_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil && x.CurrentWin != nil {
		return *x.CurrentWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetFree() bool {
	if x != nil && x.Free != nil {
		return *x.Free
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetWinInfo() *Yhwy_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetScatterCount() int64 {
	if x != nil && x.ScatterCount != nil {
		return *x.ScatterCount
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetIsGameOver() bool {
	if x != nil && x.IsGameOver != nil {
		return *x.IsGameOver
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetEffectCards() []int64 {
	if x != nil {
		return x.EffectCards
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetFinalCards() []int64 {
	if x != nil {
		return x.FinalCards
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetRevealSymbol() int64 {
	if x != nil && x.RevealSymbol != nil {
		return *x.RevealSymbol
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetSpreadToReel() int64 {
	if x != nil && x.SpreadToReel != nil {
		return *x.SpreadToReel
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetIsSakuraReset() bool {
	if x != nil && x.IsSakuraReset != nil {
		return *x.IsSakuraReset
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetResetDirection() int64 {
	if x != nil && x.ResetDirection != nil {
		return *x.ResetDirection
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetLineMultiplier() int64 {
	if x != nil && x.LineMultiplier != nil {
		return *x.LineMultiplier
	}
	return 0
}

// yhwy_WinInfo 汇总本次 step 的中奖线与免费次数变化。
type Yhwy_WinInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WinArr         []*Yhwy_WinArr         `protobuf:"bytes,1,rep,name=winArr,proto3" json:"winArr,omitempty"`                        // 本次命中的所有中奖线
	AddFreeNum     *int64                 `protobuf:"varint,2,opt,name=addFreeNum,proto3,oneof" json:"addFreeNum,omitempty"`         // 本次新增的免费次数
	LineMultiplier *int64                 `protobuf:"varint,3,opt,name=lineMultiplier,proto3,oneof" json:"lineMultiplier,omitempty"` // 本次所有中奖线赔率之和
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Yhwy_WinInfo) Reset() {
	*x = Yhwy_WinInfo{}
	mi := &file_pb_yhwy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_WinInfo) ProtoMessage() {}

func (x *Yhwy_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_yhwy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_WinInfo.ProtoReflect.Descriptor instead.
func (*Yhwy_WinInfo) Descriptor() ([]byte, []int) {
	return file_pb_yhwy_proto_rawDescGZIP(), []int{1}
}

func (x *Yhwy_WinInfo) GetWinArr() []*Yhwy_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Yhwy_WinInfo) GetAddFreeNum() int64 {
	if x != nil && x.AddFreeNum != nil {
		return *x.AddFreeNum
	}
	return 0
}

func (x *Yhwy_WinInfo) GetLineMultiplier() int64 {
	if x != nil && x.LineMultiplier != nil {
		return *x.LineMultiplier
	}
	return 0
}

// yhwy_WinArr 描述单条中奖线。
type Yhwy_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       *int64                 `protobuf:"varint,1,opt,name=roadNum,proto3,oneof" json:"roadNum,omitempty"` // 中奖线编号，从 0 开始
	Odds          *int64                 `protobuf:"varint,2,opt,name=odds,proto3,oneof" json:"odds,omitempty"`       // 该中奖线赔率
	Symbol        *int64                 `protobuf:"varint,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`   // 该中奖线命中的主符号
	Count         *int64                 `protobuf:"varint,4,opt,name=count,proto3,oneof" json:"count,omitempty"`     // 连续命中的数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Yhwy_WinArr) Reset() {
	*x = Yhwy_WinArr{}
	mi := &file_pb_yhwy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_WinArr) ProtoMessage() {}

func (x *Yhwy_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_pb_yhwy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_WinArr.ProtoReflect.Descriptor instead.
func (*Yhwy_WinArr) Descriptor() ([]byte, []int) {
	return file_pb_yhwy_proto_rawDescGZIP(), []int{2}
}

func (x *Yhwy_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Yhwy_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

func (x *Yhwy_WinArr) GetSymbol() int64 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *Yhwy_WinArr) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

var File_pb_yhwy_proto protoreflect.FileDescriptor

const file_pb_yhwy_proto_rawDesc = "" +
	"\n" +
	"\rpb/yhwy.proto\x12\x04yhwy\"\xfa\b\n" +
	"\x15yhwy_BetOrderResponse\x12\x1d\n" +
	"\aorderSN\x18\x01 \x01(\tH\x00R\aorderSN\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01H\x03R\n" +
	"currentWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\x05 \x01(\x01H\x04R\afreeWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\x06 \x01(\x01H\x05R\btotalWin\x88\x01\x01\x12\x17\n" +
	"\x04free\x18\a \x01(\bH\x06R\x04free\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\b \x01(\x03H\aR\x06review\x88\x01\x01\x121\n" +
	"\awinInfo\x18\t \x01(\v2\x12.yhwy.yhwy_WinInfoH\bR\awinInfo\x88\x01\x01\x12\x14\n" +
	"\x05cards\x18\n" +
	" \x03(\x03R\x05cards\x12'\n" +
	"\fscatterCount\x18\v \x01(\x03H\tR\fscatterCount\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\f \x01(\bH\n" +
	"R\visRoundOver\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\r \x01(\x03H\vR\x05state\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\x0e \x01(\x03H\fR\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\x0f \x01(\x03H\rR\bfreeTime\x88\x01\x01\x12\x18\n" +
	"\awinGrid\x18\x10 \x03(\x03R\awinGrid\x12#\n" +
	"\n" +
	"isGameOver\x18\x11 \x01(\bH\x0eR\n" +
	"isGameOver\x88\x01\x01\x12 \n" +
	"\veffectCards\x18\x12 \x03(\x03R\veffectCards\x12\x1e\n" +
	"\n" +
	"finalCards\x18\x13 \x03(\x03R\n" +
	"finalCards\x12'\n" +
	"\frevealSymbol\x18\x14 \x01(\x03H\x0fR\frevealSymbol\x88\x01\x01\x12'\n" +
	"\fspreadToReel\x18\x15 \x01(\x03H\x10R\fspreadToReel\x88\x01\x01\x12)\n" +
	"\risSakuraReset\x18\x16 \x01(\bH\x11R\risSakuraReset\x88\x01\x01\x12+\n" +
	"\x0eresetDirection\x18\x17 \x01(\x03H\x12R\x0eresetDirection\x88\x01\x01\x12+\n" +
	"\x0elineMultiplier\x18\x18 \x01(\x03H\x13R\x0elineMultiplier\x88\x01\x01B\n" +
	"\n" +
	"\b_orderSNB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_currentWinB\n" +
	"\n" +
	"\b_freeWinB\v\n" +
	"\t_totalWinB\a\n" +
	"\x05_freeB\t\n" +
	"\a_reviewB\n" +
	"\n" +
	"\b_winInfoB\x0f\n" +
	"\r_scatterCountB\x0e\n" +
	"\f_isRoundOverB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\r\n" +
	"\v_isGameOverB\x0f\n" +
	"\r_revealSymbolB\x0f\n" +
	"\r_spreadToReelB\x10\n" +
	"\x0e_isSakuraResetB\x11\n" +
	"\x0f_resetDirectionB\x11\n" +
	"\x0f_lineMultiplier\"\xad\x01\n" +
	"\fyhwy_WinInfo\x12)\n" +
	"\x06winArr\x18\x01 \x03(\v2\x11.yhwy.yhwy_WinArrR\x06winArr\x12#\n" +
	"\n" +
	"addFreeNum\x18\x02 \x01(\x03H\x00R\n" +
	"addFreeNum\x88\x01\x01\x12+\n" +
	"\x0elineMultiplier\x18\x03 \x01(\x03H\x01R\x0elineMultiplier\x88\x01\x01B\r\n" +
	"\v_addFreeNumB\x11\n" +
	"\x0f_lineMultiplier\"\xa7\x01\n" +
	"\vyhwy_WinArr\x12\x1d\n" +
	"\aroadNum\x18\x01 \x01(\x03H\x00R\aroadNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x02 \x01(\x03H\x01R\x04odds\x88\x01\x01\x12\x1b\n" +
	"\x06symbol\x18\x03 \x01(\x03H\x02R\x06symbol\x88\x01\x01\x12\x19\n" +
	"\x05count\x18\x04 \x01(\x03H\x03R\x05count\x88\x01\x01B\n" +
	"\n" +
	"\b_roadNumB\a\n" +
	"\x05_oddsB\t\n" +
	"\a_symbolB\b\n" +
	"\x06_countB\x19Z\x17egame-grpc/game/yhwy/pbb\x06proto3"

var (
	file_pb_yhwy_proto_rawDescOnce sync.Once
	file_pb_yhwy_proto_rawDescData []byte
)

func file_pb_yhwy_proto_rawDescGZIP() []byte {
	file_pb_yhwy_proto_rawDescOnce.Do(func() {
		file_pb_yhwy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_yhwy_proto_rawDesc), len(file_pb_yhwy_proto_rawDesc)))
	})
	return file_pb_yhwy_proto_rawDescData
}

var file_pb_yhwy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_yhwy_proto_goTypes = []any{
	(*Yhwy_BetOrderResponse)(nil), // 0: yhwy.yhwy_BetOrderResponse
	(*Yhwy_WinInfo)(nil),          // 1: yhwy.yhwy_WinInfo
	(*Yhwy_WinArr)(nil),           // 2: yhwy.yhwy_WinArr
}
var file_pb_yhwy_proto_depIdxs = []int32{
	1, // 0: yhwy.yhwy_BetOrderResponse.winInfo:type_name -> yhwy.yhwy_WinInfo
	2, // 1: yhwy.yhwy_WinInfo.winArr:type_name -> yhwy.yhwy_WinArr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_yhwy_proto_init() }
func file_pb_yhwy_proto_init() {
	if File_pb_yhwy_proto != nil {
		return
	}
	file_pb_yhwy_proto_msgTypes[0].OneofWrappers = []any{}
	file_pb_yhwy_proto_msgTypes[1].OneofWrappers = []any{}
	file_pb_yhwy_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_yhwy_proto_rawDesc), len(file_pb_yhwy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_yhwy_proto_goTypes,
		DependencyIndexes: file_pb_yhwy_proto_depIdxs,
		MessageInfos:      file_pb_yhwy_proto_msgTypes,
	}.Build()
	File_pb_yhwy_proto = out.File
	file_pb_yhwy_proto_goTypes = nil
	file_pb_yhwy_proto_depIdxs = nil
}
