// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: yhwy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// yhwy_BetOrderResponse 是单次下注返回给前端的完整结果。
type Yhwy_BetOrderResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sn                 *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn,omitempty"`                                   // 订单号
	Balance            *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`                       // 玩家当前余额
	BetAmount          *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`                   // 本局下注金额 (baseMoney * multiple * 50)
	CurWin             *float64               `protobuf:"fixed64,4,opt,name=curWin,proto3,oneof" json:"curWin,omitempty"`                         // 本局赢取金额
	FreeTotalWin       *float64               `protobuf:"fixed64,5,opt,name=freeTotalWin,proto3,oneof" json:"freeTotalWin,omitempty"`             // 免费游戏累计赢取 (ClientOfFreeGame.GetFreeTotalMoney)
	TotalWin           *float64               `protobuf:"fixed64,6,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`                     // 本回合总赢取 (ClientOfFreeGame.GetGeneralWinTotal)
	IsFree             *bool                  `protobuf:"varint,7,opt,name=isFree,proto3,oneof" json:"isFree,omitempty"`                          // 是否处于免费模式
	Review             *int64                 `protobuf:"varint,8,opt,name=review,proto3,oneof" json:"review,omitempty"`                          // 复盘标志 1=复盘 0=正常
	WinInfo            *Yhwy_WinInfo          `protobuf:"bytes,9,opt,name=winInfo,proto3,oneof" json:"winInfo,omitempty"`                         // 中奖详情
	Cards              []int64                `protobuf:"varint,10,rep,packed,name=cards,proto3" json:"cards,omitempty"`                          // 符号网格 8×5，按行优先 elements共40个（服务端方向，不翻转）
	ScatterCount       *int64                 `protobuf:"varint,11,opt,name=scatterCount,proto3,oneof" json:"scatterCount,omitempty"`             // Scatter 个数（Base=底4行；Free=已解锁行）
	IsRoundOver        *bool                  `protobuf:"varint,12,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver,omitempty"`               // 是否本局结束
	State              *int64                 `protobuf:"varint,13,opt,name=state,proto3,oneof" json:"state,omitempty"`                           // 游戏状态 0=普通 1=免费
	RemainingFreeTimes *int64                 `protobuf:"varint,14,opt,name=remainingFreeTimes,proto3,oneof" json:"remainingFreeTimes,omitempty"` // 剩余免费次数 ClientOfFreeGame.GetFreeNum
	TotalFreeTimes     *int64                 `protobuf:"varint,15,opt,name=totalFreeTimes,proto3,oneof" json:"totalFreeTimes,omitempty"`         // 已使用免费次数 ClientOfFreeGame.GetFreeTimes
	WinGrid            []int64                `protobuf:"varint,16,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`                      // 中奖位置网格 8×5（仅标记底4行，1=中奖位 0=未中奖）
	IsGameOver         *bool                  `protobuf:"varint,17,opt,name=isGameOver,proto3,oneof" json:"isGameOver,omitempty"`                 // 大回合结束
	LineMultiplier     *int64                 `protobuf:"varint,18,opt,name=lineMultiplier,proto3,oneof" json:"lineMultiplier,omitempty"`         // 本次所有中奖线赔率之和
	MysGrid            []int64                `protobuf:"varint,19,rep,packed,name=mysGrid,proto3" json:"mysGrid,omitempty"`                      // 百变樱花盘面
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Yhwy_BetOrderResponse) Reset() {
	*x = Yhwy_BetOrderResponse{}
	mi := &file_yhwy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_BetOrderResponse) ProtoMessage() {}

func (x *Yhwy_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yhwy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Yhwy_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_yhwy_proto_rawDescGZIP(), []int{0}
}

func (x *Yhwy_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Yhwy_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetFreeTotalWin() float64 {
	if x != nil && x.FreeTotalWin != nil {
		return *x.FreeTotalWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetWinInfo() *Yhwy_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetScatterCount() int64 {
	if x != nil && x.ScatterCount != nil {
		return *x.ScatterCount
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetRemainingFreeTimes() int64 {
	if x != nil && x.RemainingFreeTimes != nil {
		return *x.RemainingFreeTimes
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetTotalFreeTimes() int64 {
	if x != nil && x.TotalFreeTimes != nil {
		return *x.TotalFreeTimes
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetIsGameOver() bool {
	if x != nil && x.IsGameOver != nil {
		return *x.IsGameOver
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetLineMultiplier() int64 {
	if x != nil && x.LineMultiplier != nil {
		return *x.LineMultiplier
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetMysGrid() []int64 {
	if x != nil {
		return x.MysGrid
	}
	return nil
}

// yhwy_WinInfo 汇总本次 step 的中奖线与免费次数变化。
type Yhwy_WinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinArr        []*Yhwy_WinArr         `protobuf:"bytes,1,rep,name=winArr,proto3" json:"winArr,omitempty"`                // 本次命中的所有中奖线
	AddFreeNum    *int64                 `protobuf:"varint,2,opt,name=addFreeNum,proto3,oneof" json:"addFreeNum,omitempty"` // 本次新增的免费次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Yhwy_WinInfo) Reset() {
	*x = Yhwy_WinInfo{}
	mi := &file_yhwy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_WinInfo) ProtoMessage() {}

func (x *Yhwy_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yhwy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_WinInfo.ProtoReflect.Descriptor instead.
func (*Yhwy_WinInfo) Descriptor() ([]byte, []int) {
	return file_yhwy_proto_rawDescGZIP(), []int{1}
}

func (x *Yhwy_WinInfo) GetWinArr() []*Yhwy_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Yhwy_WinInfo) GetAddFreeNum() int64 {
	if x != nil && x.AddFreeNum != nil {
		return *x.AddFreeNum
	}
	return 0
}

// yhwy_WinArr 描述单条中奖线。
type Yhwy_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       *int64                 `protobuf:"varint,1,opt,name=roadNum,proto3,oneof" json:"roadNum,omitempty"` // 中奖线编号，从 0 开始
	Odds          *int64                 `protobuf:"varint,2,opt,name=odds,proto3,oneof" json:"odds,omitempty"`       // 该中奖线赔率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Yhwy_WinArr) Reset() {
	*x = Yhwy_WinArr{}
	mi := &file_yhwy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_WinArr) ProtoMessage() {}

func (x *Yhwy_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_yhwy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_WinArr.ProtoReflect.Descriptor instead.
func (*Yhwy_WinArr) Descriptor() ([]byte, []int) {
	return file_yhwy_proto_rawDescGZIP(), []int{2}
}

func (x *Yhwy_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Yhwy_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

var File_yhwy_proto protoreflect.FileDescriptor

const file_yhwy_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"yhwy.proto\x12\x04yhwy\"\x8e\a\n" +
	"\x15yhwy_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x04 \x01(\x01H\x03R\x06curWin\x88\x01\x01\x12'\n" +
	"\ffreeTotalWin\x18\x05 \x01(\x01H\x04R\ffreeTotalWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\x06 \x01(\x01H\x05R\btotalWin\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\a \x01(\bH\x06R\x06isFree\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\b \x01(\x03H\aR\x06review\x88\x01\x01\x121\n" +
	"\awinInfo\x18\t \x01(\v2\x12.yhwy.yhwy_WinInfoH\bR\awinInfo\x88\x01\x01\x12\x14\n" +
	"\x05cards\x18\n" +
	" \x03(\x03R\x05cards\x12'\n" +
	"\fscatterCount\x18\v \x01(\x03H\tR\fscatterCount\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\f \x01(\bH\n" +
	"R\visRoundOver\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\r \x01(\x03H\vR\x05state\x88\x01\x01\x123\n" +
	"\x12remainingFreeTimes\x18\x0e \x01(\x03H\fR\x12remainingFreeTimes\x88\x01\x01\x12+\n" +
	"\x0etotalFreeTimes\x18\x0f \x01(\x03H\rR\x0etotalFreeTimes\x88\x01\x01\x12\x18\n" +
	"\awinGrid\x18\x10 \x03(\x03R\awinGrid\x12#\n" +
	"\n" +
	"isGameOver\x18\x11 \x01(\bH\x0eR\n" +
	"isGameOver\x88\x01\x01\x12+\n" +
	"\x0elineMultiplier\x18\x12 \x01(\x03H\x0fR\x0elineMultiplier\x88\x01\x01\x12\x18\n" +
	"\amysGrid\x18\x13 \x03(\x03R\amysGridB\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\t\n" +
	"\a_curWinB\x0f\n" +
	"\r_freeTotalWinB\v\n" +
	"\t_totalWinB\t\n" +
	"\a_isFreeB\t\n" +
	"\a_reviewB\n" +
	"\n" +
	"\b_winInfoB\x0f\n" +
	"\r_scatterCountB\x0e\n" +
	"\f_isRoundOverB\b\n" +
	"\x06_stateB\x15\n" +
	"\x13_remainingFreeTimesB\x11\n" +
	"\x0f_totalFreeTimesB\r\n" +
	"\v_isGameOverB\x11\n" +
	"\x0f_lineMultiplier\"m\n" +
	"\fyhwy_WinInfo\x12)\n" +
	"\x06winArr\x18\x01 \x03(\v2\x11.yhwy.yhwy_WinArrR\x06winArr\x12#\n" +
	"\n" +
	"addFreeNum\x18\x02 \x01(\x03H\x00R\n" +
	"addFreeNum\x88\x01\x01B\r\n" +
	"\v_addFreeNum\"Z\n" +
	"\vyhwy_WinArr\x12\x1d\n" +
	"\aroadNum\x18\x01 \x01(\x03H\x00R\aroadNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x02 \x01(\x03H\x01R\x04odds\x88\x01\x01B\n" +
	"\n" +
	"\b_roadNumB\a\n" +
	"\x05_oddsB\x19Z\x17egame-grpc/game/yhwy/pbb\x06proto3"

var (
	file_yhwy_proto_rawDescOnce sync.Once
	file_yhwy_proto_rawDescData []byte
)

func file_yhwy_proto_rawDescGZIP() []byte {
	file_yhwy_proto_rawDescOnce.Do(func() {
		file_yhwy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yhwy_proto_rawDesc), len(file_yhwy_proto_rawDesc)))
	})
	return file_yhwy_proto_rawDescData
}

var file_yhwy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_yhwy_proto_goTypes = []any{
	(*Yhwy_BetOrderResponse)(nil), // 0: yhwy.yhwy_BetOrderResponse
	(*Yhwy_WinInfo)(nil),          // 1: yhwy.yhwy_WinInfo
	(*Yhwy_WinArr)(nil),           // 2: yhwy.yhwy_WinArr
}
var file_yhwy_proto_depIdxs = []int32{
	1, // 0: yhwy.yhwy_BetOrderResponse.winInfo:type_name -> yhwy.yhwy_WinInfo
	2, // 1: yhwy.yhwy_WinInfo.winArr:type_name -> yhwy.yhwy_WinArr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_yhwy_proto_init() }
func file_yhwy_proto_init() {
	if File_yhwy_proto != nil {
		return
	}
	file_yhwy_proto_msgTypes[0].OneofWrappers = []any{}
	file_yhwy_proto_msgTypes[1].OneofWrappers = []any{}
	file_yhwy_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yhwy_proto_rawDesc), len(file_yhwy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yhwy_proto_goTypes,
		DependencyIndexes: file_yhwy_proto_depIdxs,
		MessageInfos:      file_yhwy_proto_msgTypes,
	}.Build()
	File_yhwy_proto = out.File
	file_yhwy_proto_goTypes = nil
	file_yhwy_proto_depIdxs = nil
}
