// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: bxkh2.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 巴西狂欢 (GameID: 18965)
// 盘面: 6x6
// 特色: 免费模式、连消进阶倍率、长符号转化
type Bxkh2_BetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn"`                          // 订单号
	Balance       *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"`              // 当前余额
	BaseBet       *float64               `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet"`              // 基础下注
	Multiplier    *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier"`         // 下注倍数
	BetAmount     *float64               `protobuf:"fixed64,5,opt,name=betAmount,proto3,oneof" json:"betAmount"`          // 实际投注金额（baseBet × multiplier × baseMultiple）
	CurWin        *float64               `protobuf:"fixed64,6,opt,name=curWin,proto3,oneof" json:"curWin"`                // step：本次 betOrder 赢分
	RoundWin      *float64               `protobuf:"fixed64,7,opt,name=roundWin,proto3,oneof" json:"roundWin"`            // round：本回合累计赢（连消多步累计）
	TotalWin      *float64               `protobuf:"fixed64,8,opt,name=totalWin,proto3,oneof" json:"totalWin"`            // spin：本 spin 总赢（含免费触发轮）
	FreeWin       *float64               `protobuf:"fixed64,9,opt,name=freeWin,proto3,oneof" json:"freeWin"`              // 免费局阶段累计总赢（不含触发轮）
	IsRoundOver   *bool                  `protobuf:"varint,10,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver"`      // 本 round 是否结束
	IsFree        *bool                  `protobuf:"varint,11,opt,name=isFree,proto3,oneof" json:"isFree"`                // 当前是否处于免费游戏
	FreeNum       *int64                 `protobuf:"varint,12,opt,name=freeNum,proto3,oneof" json:"freeNum"`              // 剩余免费次数
	FreeTime      *int64                 `protobuf:"varint,13,opt,name=freeTime,proto3,oneof" json:"freeTime"`            // 已使用免费次数
	NewFreeTimes  *int64                 `protobuf:"varint,14,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes"`    // 本步新增的免费旋转次数
	SymGrid       []int64                `protobuf:"varint,15,rep,packed,name=symGrid,proto3" json:"symGrid"`             // 本步牌面（6x6，按行展开）
	WinGrid       []int64                `protobuf:"varint,16,rep,packed,name=winGrid,proto3" json:"winGrid"`             // 中奖位置网格（与 symGrid 同序）
	WinArr        []*Bxkh2_WinArr        `protobuf:"bytes,17,rep,name=winArr,proto3" json:"winArr"`                       // 本次命中的所有中奖线明细
	FreeMultiple  *int64                 `protobuf:"varint,18,opt,name=freeMultiple,proto3,oneof" json:"freeMultiple"`    // 免费局连消倍率（1,2,3...）
	OriginalCards []int64                `protobuf:"varint,19,rep,packed,name=originalCards,proto3" json:"originalCards"` // 转化/下落前原始牌面（展示用途）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bxkh2_BetOrderResponse) Reset() {
	*x = Bxkh2_BetOrderResponse{}
	mi := &file_bxkh2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bxkh2_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bxkh2_BetOrderResponse) ProtoMessage() {}

func (x *Bxkh2_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bxkh2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bxkh2_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Bxkh2_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_bxkh2_proto_rawDescGZIP(), []int{0}
}

func (x *Bxkh2_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Bxkh2_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Bxkh2_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Bxkh2_BetOrderResponse) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetSymGrid() []int64 {
	if x != nil {
		return x.SymGrid
	}
	return nil
}

func (x *Bxkh2_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Bxkh2_BetOrderResponse) GetWinArr() []*Bxkh2_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Bxkh2_BetOrderResponse) GetFreeMultiple() int64 {
	if x != nil && x.FreeMultiple != nil {
		return *x.FreeMultiple
	}
	return 0
}

func (x *Bxkh2_BetOrderResponse) GetOriginalCards() []int64 {
	if x != nil {
		return x.OriginalCards
	}
	return nil
}

type Bxkh2_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *int64                 `protobuf:"varint,1,opt,name=val,proto3,oneof" json:"val"`         // 中奖符号
	RoadNum       *int64                 `protobuf:"varint,2,opt,name=roadNum,proto3,oneof" json:"roadNum"` // 中奖路数（线数积）
	StarNum       *int64                 `protobuf:"varint,3,opt,name=starNum,proto3,oneof" json:"starNum"` // 连续命中列数
	Odds          *int64                 `protobuf:"varint,4,opt,name=odds,proto3,oneof" json:"odds"`       // 赔率
	Mul           *int64                 `protobuf:"varint,5,opt,name=mul,proto3,oneof" json:"mul"`         // 倍率（roadNum × odds）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bxkh2_WinArr) Reset() {
	*x = Bxkh2_WinArr{}
	mi := &file_bxkh2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bxkh2_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bxkh2_WinArr) ProtoMessage() {}

func (x *Bxkh2_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_bxkh2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bxkh2_WinArr.ProtoReflect.Descriptor instead.
func (*Bxkh2_WinArr) Descriptor() ([]byte, []int) {
	return file_bxkh2_proto_rawDescGZIP(), []int{1}
}

func (x *Bxkh2_WinArr) GetVal() int64 {
	if x != nil && x.Val != nil {
		return *x.Val
	}
	return 0
}

func (x *Bxkh2_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Bxkh2_WinArr) GetStarNum() int64 {
	if x != nil && x.StarNum != nil {
		return *x.StarNum
	}
	return 0
}

func (x *Bxkh2_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

func (x *Bxkh2_WinArr) GetMul() int64 {
	if x != nil && x.Mul != nil {
		return *x.Mul
	}
	return 0
}

var File_bxkh2_proto protoreflect.FileDescriptor

const file_bxkh2_proto_rawDesc = "" +
	"\n" +
	"\vbxkh2.proto\x12\x05bxkh2\"\xd1\x06\n" +
	"\x16bxkh2_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x05 \x01(\x01H\x04R\tbetAmount\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x06 \x01(\x01H\x05R\x06curWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\a \x01(\x01H\x06R\broundWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\b \x01(\x01H\aR\btotalWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\t \x01(\x01H\bR\afreeWin\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\n" +
	" \x01(\bH\tR\visRoundOver\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\v \x01(\bH\n" +
	"R\x06isFree\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\f \x01(\x03H\vR\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\r \x01(\x03H\fR\bfreeTime\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\x0e \x01(\x03H\rR\fnewFreeTimes\x88\x01\x01\x12\x18\n" +
	"\asymGrid\x18\x0f \x03(\x03R\asymGrid\x12\x18\n" +
	"\awinGrid\x18\x10 \x03(\x03R\awinGrid\x12+\n" +
	"\x06winArr\x18\x11 \x03(\v2\x13.bxkh2.bxkh2_WinArrR\x06winArr\x12'\n" +
	"\ffreeMultiple\x18\x12 \x01(\x03H\x0eR\ffreeMultiple\x88\x01\x01\x12$\n" +
	"\roriginalCards\x18\x13 \x03(\x03R\roriginalCardsB\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\r\n" +
	"\v_multiplierB\f\n" +
	"\n" +
	"_betAmountB\t\n" +
	"\a_curWinB\v\n" +
	"\t_roundWinB\v\n" +
	"\t_totalWinB\n" +
	"\n" +
	"\b_freeWinB\x0e\n" +
	"\f_isRoundOverB\t\n" +
	"\a_isFreeB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\x0f\n" +
	"\r_newFreeTimesB\x0f\n" +
	"\r_freeMultiple\"\xc4\x01\n" +
	"\fbxkh2_WinArr\x12\x15\n" +
	"\x03val\x18\x01 \x01(\x03H\x00R\x03val\x88\x01\x01\x12\x1d\n" +
	"\aroadNum\x18\x02 \x01(\x03H\x01R\aroadNum\x88\x01\x01\x12\x1d\n" +
	"\astarNum\x18\x03 \x01(\x03H\x02R\astarNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x04 \x01(\x03H\x03R\x04odds\x88\x01\x01\x12\x15\n" +
	"\x03mul\x18\x05 \x01(\x03H\x04R\x03mul\x88\x01\x01B\x06\n" +
	"\x04_valB\n" +
	"\n" +
	"\b_roadNumB\n" +
	"\n" +
	"\b_starNumB\a\n" +
	"\x05_oddsB\x06\n" +
	"\x04_mulB\x1aZ\x18egame-grpc/game/bxkh2/pbb\x06proto3"

var (
	file_bxkh2_proto_rawDescOnce sync.Once
	file_bxkh2_proto_rawDescData []byte
)

func file_bxkh2_proto_rawDescGZIP() []byte {
	file_bxkh2_proto_rawDescOnce.Do(func() {
		file_bxkh2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bxkh2_proto_rawDesc), len(file_bxkh2_proto_rawDesc)))
	})
	return file_bxkh2_proto_rawDescData
}

var file_bxkh2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bxkh2_proto_goTypes = []any{
	(*Bxkh2_BetOrderResponse)(nil), // 0: bxkh2.bxkh2_BetOrderResponse
	(*Bxkh2_WinArr)(nil),           // 1: bxkh2.bxkh2_WinArr
}
var file_bxkh2_proto_depIdxs = []int32{
	1, // 0: bxkh2.bxkh2_BetOrderResponse.winArr:type_name -> bxkh2.bxkh2_WinArr
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bxkh2_proto_init() }
func file_bxkh2_proto_init() {
	if File_bxkh2_proto != nil {
		return
	}
	file_bxkh2_proto_msgTypes[0].OneofWrappers = []any{}
	file_bxkh2_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bxkh2_proto_rawDesc), len(file_bxkh2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bxkh2_proto_goTypes,
		DependencyIndexes: file_bxkh2_proto_depIdxs,
		MessageInfos:      file_bxkh2_proto_msgTypes,
	}.Build()
	File_bxkh2_proto = out.File
	file_bxkh2_proto_goTypes = nil
	file_bxkh2_proto_depIdxs = nil
}
