// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: hcsqy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hcsqy_BetOrderResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderSN          *string                `protobuf:"bytes,1,opt,name=orderSN,proto3,oneof" json:"orderSN"`                     // 订单号
	Balance          *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"`                   // 玩家当前余额
	BetAmount        *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount"`               // 本局下注金额 (baseMoney * multiple * 5)
	CurrentWin       *float64               `protobuf:"fixed64,4,opt,name=currentWin,proto3,oneof" json:"currentWin"`             // 本局赢取金额
	FreeWin          *float64               `protobuf:"fixed64,5,opt,name=freeWin,proto3,oneof" json:"freeWin"`                   // 免费游戏累计赢取
	TotalWin         *float64               `protobuf:"fixed64,6,opt,name=totalWin,proto3,oneof" json:"totalWin"`                 // 本回合总赢取
	Free             *bool                  `protobuf:"varint,7,opt,name=free,proto3,oneof" json:"free"`                          // 是否处于免费模式
	Review           *int64                 `protobuf:"varint,8,opt,name=review,proto3,oneof" json:"review"`                      // 复盘标志 1=复盘 0=正常
	WinInfo          *Hcsqy_WinInfo         `protobuf:"bytes,9,opt,name=winInfo,proto3,oneof" json:"winInfo"`                     // 中奖详情
	Cards            []int64                `protobuf:"varint,10,rep,packed,name=cards,proto3" json:"cards"`                      // 符号网格 3x3，按行优先 elements共9个
	ScatterCount     *int64                 `protobuf:"varint,11,opt,name=scatterCount,proto3,oneof" json:"scatterCount"`         // 夺宝符个数
	IsRoundOver      *bool                  `protobuf:"varint,12,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver"`           // 是否本局结束
	State            *int64                 `protobuf:"varint,13,opt,name=state,proto3,oneof" json:"state"`                       // 游戏状态 1=普通 2=免费 11=购买基础 12=购买免费
	FreeNum          *int64                 `protobuf:"varint,14,opt,name=freeNum,proto3,oneof" json:"freeNum"`                   // 剩余免费次数
	FreeTime         *int64                 `protobuf:"varint,15,opt,name=freeTime,proto3,oneof" json:"freeTime"`                 // 已使用免费次数
	WinGrid          []int64                `protobuf:"varint,16,rep,packed,name=winGrid,proto3" json:"winGrid"`                  // 中奖位置网格 3x3
	IsGameOver       *bool                  `protobuf:"varint,17,opt,name=isGameOver,proto3,oneof" json:"isGameOver"`             // 大回合结束
	Next             *bool                  `protobuf:"varint,18,opt,name=next,proto3,oneof" json:"next"`                         // 是否需要继续请求（重转至赢）
	IsRespinUntilWin *bool                  `protobuf:"varint,19,opt,name=isRespinUntilWin,proto3,oneof" json:"isRespinUntilWin"` // 是否在重转至赢模式中 (有炸胡动画)
	RespinWildCol    *int32                 `protobuf:"varint,20,opt,name=respinWildCol,proto3,oneof" json:"respinWildCol"`       // 重转至赢模式长条百搭列 (0-2)，非重转模式为-1
	WildMultiplier   *int64                 `protobuf:"varint,21,opt,name=wildMultiplier,proto3,oneof" json:"wildMultiplier"`     // 长条百搭倍数 (x2-x20)
	LineMultiplier   *int64                 `protobuf:"varint,22,opt,name=lineMultiplier,proto3,oneof" json:"lineMultiplier"`     // 线赔率合计（各中奖线基础赔率之和，未乘长条百搭）
	IsPurchase       *bool                  `protobuf:"varint,23,opt,name=isPurchase,proto3,oneof" json:"isPurchase"`             // 当前大回合是否购买免费触发
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Hcsqy_BetOrderResponse) Reset() {
	*x = Hcsqy_BetOrderResponse{}
	mi := &file_hcsqy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hcsqy_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hcsqy_BetOrderResponse) ProtoMessage() {}

func (x *Hcsqy_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hcsqy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hcsqy_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Hcsqy_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_hcsqy_proto_rawDescGZIP(), []int{0}
}

func (x *Hcsqy_BetOrderResponse) GetOrderSN() string {
	if x != nil && x.OrderSN != nil {
		return *x.OrderSN
	}
	return ""
}

func (x *Hcsqy_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil && x.CurrentWin != nil {
		return *x.CurrentWin
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetFree() bool {
	if x != nil && x.Free != nil {
		return *x.Free
	}
	return false
}

func (x *Hcsqy_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetWinInfo() *Hcsqy_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Hcsqy_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Hcsqy_BetOrderResponse) GetScatterCount() int64 {
	if x != nil && x.ScatterCount != nil {
		return *x.ScatterCount
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Hcsqy_BetOrderResponse) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Hcsqy_BetOrderResponse) GetIsGameOver() bool {
	if x != nil && x.IsGameOver != nil {
		return *x.IsGameOver
	}
	return false
}

func (x *Hcsqy_BetOrderResponse) GetNext() bool {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return false
}

func (x *Hcsqy_BetOrderResponse) GetIsRespinUntilWin() bool {
	if x != nil && x.IsRespinUntilWin != nil {
		return *x.IsRespinUntilWin
	}
	return false
}

func (x *Hcsqy_BetOrderResponse) GetRespinWildCol() int32 {
	if x != nil && x.RespinWildCol != nil {
		return *x.RespinWildCol
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetWildMultiplier() int64 {
	if x != nil && x.WildMultiplier != nil {
		return *x.WildMultiplier
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetLineMultiplier() int64 {
	if x != nil && x.LineMultiplier != nil {
		return *x.LineMultiplier
	}
	return 0
}

func (x *Hcsqy_BetOrderResponse) GetIsPurchase() bool {
	if x != nil && x.IsPurchase != nil {
		return *x.IsPurchase
	}
	return false
}

// hcsqy_WinInfo 中奖详情
type Hcsqy_WinInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WinArr           []*Hcsqy_WinArr        `protobuf:"bytes,1,rep,name=winArr,proto3" json:"winArr"`                            // 本步各条中奖线的详情
	AddFreeNum       *int64                 `protobuf:"varint,2,opt,name=addFreeNum,proto3,oneof" json:"addFreeNum"`             // 增加的免费次数
	FreeGameMultiple *int64                 `protobuf:"varint,3,opt,name=freeGameMultiple,proto3,oneof" json:"freeGameMultiple"` // 本步倍数 (lineMultiplier * wildMultiplier)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Hcsqy_WinInfo) Reset() {
	*x = Hcsqy_WinInfo{}
	mi := &file_hcsqy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hcsqy_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hcsqy_WinInfo) ProtoMessage() {}

func (x *Hcsqy_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hcsqy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hcsqy_WinInfo.ProtoReflect.Descriptor instead.
func (*Hcsqy_WinInfo) Descriptor() ([]byte, []int) {
	return file_hcsqy_proto_rawDescGZIP(), []int{1}
}

func (x *Hcsqy_WinInfo) GetWinArr() []*Hcsqy_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Hcsqy_WinInfo) GetAddFreeNum() int64 {
	if x != nil && x.AddFreeNum != nil {
		return *x.AddFreeNum
	}
	return 0
}

func (x *Hcsqy_WinInfo) GetFreeGameMultiple() int64 {
	if x != nil && x.FreeGameMultiple != nil {
		return *x.FreeGameMultiple
	}
	return 0
}

// hcsqy_WinArr 单条中奖线详情
type Hcsqy_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       *int64                 `protobuf:"varint,1,opt,name=roadNum,proto3,oneof" json:"roadNum"` // 支付线编号 0~4
	Odds          *int64                 `protobuf:"varint,2,opt,name=odds,proto3,oneof" json:"odds"`       // 基础赔率 来自 pay_table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hcsqy_WinArr) Reset() {
	*x = Hcsqy_WinArr{}
	mi := &file_hcsqy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hcsqy_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hcsqy_WinArr) ProtoMessage() {}

func (x *Hcsqy_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_hcsqy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hcsqy_WinArr.ProtoReflect.Descriptor instead.
func (*Hcsqy_WinArr) Descriptor() ([]byte, []int) {
	return file_hcsqy_proto_rawDescGZIP(), []int{2}
}

func (x *Hcsqy_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Hcsqy_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

var File_hcsqy_proto protoreflect.FileDescriptor

const file_hcsqy_proto_rawDesc = "" +
	"\n" +
	"\vhcsqy.proto\x12\x05hcsqy\"\xe3\b\n" +
	"\x16hcsqy_BetOrderResponse\x12\x1d\n" +
	"\aorderSN\x18\x01 \x01(\tH\x00R\aorderSN\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01H\x03R\n" +
	"currentWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\x05 \x01(\x01H\x04R\afreeWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\x06 \x01(\x01H\x05R\btotalWin\x88\x01\x01\x12\x17\n" +
	"\x04free\x18\a \x01(\bH\x06R\x04free\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\b \x01(\x03H\aR\x06review\x88\x01\x01\x123\n" +
	"\awinInfo\x18\t \x01(\v2\x14.hcsqy.hcsqy_WinInfoH\bR\awinInfo\x88\x01\x01\x12\x14\n" +
	"\x05cards\x18\n" +
	" \x03(\x03R\x05cards\x12'\n" +
	"\fscatterCount\x18\v \x01(\x03H\tR\fscatterCount\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\f \x01(\bH\n" +
	"R\visRoundOver\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\r \x01(\x03H\vR\x05state\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\x0e \x01(\x03H\fR\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\x0f \x01(\x03H\rR\bfreeTime\x88\x01\x01\x12\x18\n" +
	"\awinGrid\x18\x10 \x03(\x03R\awinGrid\x12#\n" +
	"\n" +
	"isGameOver\x18\x11 \x01(\bH\x0eR\n" +
	"isGameOver\x88\x01\x01\x12\x17\n" +
	"\x04next\x18\x12 \x01(\bH\x0fR\x04next\x88\x01\x01\x12/\n" +
	"\x10isRespinUntilWin\x18\x13 \x01(\bH\x10R\x10isRespinUntilWin\x88\x01\x01\x12)\n" +
	"\rrespinWildCol\x18\x14 \x01(\x05H\x11R\rrespinWildCol\x88\x01\x01\x12+\n" +
	"\x0ewildMultiplier\x18\x15 \x01(\x03H\x12R\x0ewildMultiplier\x88\x01\x01\x12+\n" +
	"\x0elineMultiplier\x18\x16 \x01(\x03H\x13R\x0elineMultiplier\x88\x01\x01\x12#\n" +
	"\n" +
	"isPurchase\x18\x17 \x01(\bH\x14R\n" +
	"isPurchase\x88\x01\x01B\n" +
	"\n" +
	"\b_orderSNB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_currentWinB\n" +
	"\n" +
	"\b_freeWinB\v\n" +
	"\t_totalWinB\a\n" +
	"\x05_freeB\t\n" +
	"\a_reviewB\n" +
	"\n" +
	"\b_winInfoB\x0f\n" +
	"\r_scatterCountB\x0e\n" +
	"\f_isRoundOverB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\r\n" +
	"\v_isGameOverB\a\n" +
	"\x05_nextB\x13\n" +
	"\x11_isRespinUntilWinB\x10\n" +
	"\x0e_respinWildColB\x11\n" +
	"\x0f_wildMultiplierB\x11\n" +
	"\x0f_lineMultiplierB\r\n" +
	"\v_isPurchase\"\xb6\x01\n" +
	"\rhcsqy_WinInfo\x12+\n" +
	"\x06winArr\x18\x01 \x03(\v2\x13.hcsqy.hcsqy_WinArrR\x06winArr\x12#\n" +
	"\n" +
	"addFreeNum\x18\x02 \x01(\x03H\x00R\n" +
	"addFreeNum\x88\x01\x01\x12/\n" +
	"\x10freeGameMultiple\x18\x03 \x01(\x03H\x01R\x10freeGameMultiple\x88\x01\x01B\r\n" +
	"\v_addFreeNumB\x13\n" +
	"\x11_freeGameMultiple\"[\n" +
	"\fhcsqy_WinArr\x12\x1d\n" +
	"\aroadNum\x18\x01 \x01(\x03H\x00R\aroadNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x02 \x01(\x03H\x01R\x04odds\x88\x01\x01B\n" +
	"\n" +
	"\b_roadNumB\a\n" +
	"\x05_oddsB\x1bZ\x19egame-grpc/game/common/pbb\x06proto3"

var (
	file_hcsqy_proto_rawDescOnce sync.Once
	file_hcsqy_proto_rawDescData []byte
)

func file_hcsqy_proto_rawDescGZIP() []byte {
	file_hcsqy_proto_rawDescOnce.Do(func() {
		file_hcsqy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hcsqy_proto_rawDesc), len(file_hcsqy_proto_rawDesc)))
	})
	return file_hcsqy_proto_rawDescData
}

var file_hcsqy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hcsqy_proto_goTypes = []any{
	(*Hcsqy_BetOrderResponse)(nil), // 0: hcsqy.hcsqy_BetOrderResponse
	(*Hcsqy_WinInfo)(nil),          // 1: hcsqy.hcsqy_WinInfo
	(*Hcsqy_WinArr)(nil),           // 2: hcsqy.hcsqy_WinArr
}
var file_hcsqy_proto_depIdxs = []int32{
	1, // 0: hcsqy.hcsqy_BetOrderResponse.winInfo:type_name -> hcsqy.hcsqy_WinInfo
	2, // 1: hcsqy.hcsqy_WinInfo.winArr:type_name -> hcsqy.hcsqy_WinArr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hcsqy_proto_init() }
func file_hcsqy_proto_init() {
	if File_hcsqy_proto != nil {
		return
	}
	file_hcsqy_proto_msgTypes[0].OneofWrappers = []any{}
	file_hcsqy_proto_msgTypes[1].OneofWrappers = []any{}
	file_hcsqy_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hcsqy_proto_rawDesc), len(file_hcsqy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hcsqy_proto_goTypes,
		DependencyIndexes: file_hcsqy_proto_depIdxs,
		MessageInfos:      file_hcsqy_proto_msgTypes,
	}.Build()
	File_hcsqy_proto = out.File
	file_hcsqy_proto_goTypes = nil
	file_hcsqy_proto_depIdxs = nil
}
