// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: 18926/jwjzy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 4行5列主盘面，3行5列奖励区，支持普通/免费模式及连续消除倍数
type Jwjzy_BetOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderSN           string                 `protobuf:"bytes,1,opt,name=orderSN,proto3" json:"orderSN,omitempty"`                          // 订单号
	Balance           float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`                        // 玩家当前余额
	BetAmount         float64                `protobuf:"fixed64,3,opt,name=betAmount,proto3" json:"betAmount,omitempty"`                    // 本局下注金额 (baseMoney * multiple * 20)
	CurrentWin        float64                `protobuf:"fixed64,4,opt,name=currentWin,proto3" json:"currentWin,omitempty"`                  // 本步赢取金额 (当前消除获得的奖金)
	FreeWin           float64                `protobuf:"fixed64,5,opt,name=freeWin,proto3" json:"freeWin,omitempty"`                        // 免费游戏累计赢取 (ClientOfFreeGame.GetFreeTotalMoney)
	TotalWin          float64                `protobuf:"fixed64,6,opt,name=totalWin,proto3" json:"totalWin,omitempty"`                      // 本回合总赢取 (ClientOfFreeGame.GetGeneralWinTotal)
	Free              bool                   `protobuf:"varint,7,opt,name=free,proto3" json:"free,omitempty"`                               // 是否处于免费模式
	Review            int64                  `protobuf:"varint,8,opt,name=review,proto3" json:"review,omitempty"`                           // 复盘标志 1=复盘 0=正常
	WinInfo           *Jwjzy_WinInfo         `protobuf:"bytes,9,opt,name=winInfo,proto3" json:"winInfo,omitempty"`                          // 中奖详情（消除结果、倍数、免费剩余等）
	Cards             []int64                `protobuf:"varint,10,rep,packed,name=cards,proto3" json:"cards,omitempty"`                     // 符号网格 4行×5列 按行优先 elements共20个
	ScatterCount      int64                  `protobuf:"varint,11,opt,name=scatterCount,proto3" json:"scatterCount,omitempty"`              // 夺宝符(9)个数 统计奖励区3行内的夺宝符
	IsRoundOver       bool                   `protobuf:"varint,12,opt,name=isRoundOver,proto3" json:"isRoundOver,omitempty"`                // 是否本局结束
	Multi             int64                  `protobuf:"varint,13,opt,name=multi,proto3" json:"multi,omitempty"`                            // 本步倍数 stepMultiplier = lineMultiplier * gameMultiple
	State             int64                  `protobuf:"varint,14,opt,name=state,proto3" json:"state,omitempty"`                            // 游戏状态 0=普通 1=免费
	FreeNum           int64                  `protobuf:"varint,15,opt,name=freeNum,proto3" json:"freeNum,omitempty"`                        // 剩余免费次数 ClientOfFreeGame.GetFreeNum
	FreeTime          int64                  `protobuf:"varint,16,opt,name=freeTime,proto3" json:"freeTime,omitempty"`                      // 已使用免费次数 ClientOfFreeGame.GetFreeTimes
	WinGrid           []int64                `protobuf:"varint,17,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`                 // 中奖位置网格 4行×5列 1标记中奖位 0未中奖
	IsGameOver        bool                   `protobuf:"varint,18,opt,name=isGameOver,proto3" json:"isGameOver,omitempty"`                  // 大回合结束
	RoundWin          float64                `protobuf:"fixed64,19,opt,name=roundWin,proto3" json:"roundWin,omitempty"`                     // 一局所有回合总赢
	MulIndex          int64                  `protobuf:"varint,20,opt,name=mulIndex,proto3" json:"mulIndex,omitempty"`                      // 当前消除轮次索引
	BaseMultipliers   []int64                `protobuf:"varint,21,rep,packed,name=baseMultipliers,proto3" json:"baseMultipliers,omitempty"` // 轮次倍数列表 [1,2,3,5]
	FreeMultipliers   []int64                `protobuf:"varint,22,rep,packed,name=freeMultipliers,proto3" json:"freeMultipliers,omitempty"` // 轮次倍数列表 [3,6,9,15]
	WildEliCount      int64                  `protobuf:"varint,23,opt,name=wildEliCount,proto3" json:"wildEliCount,omitempty"`              // 本步蝴蝶百搭个数
	TotalWildEliCount int64                  `protobuf:"varint,24,opt,name=totalWildEliCount,proto3" json:"totalWildEliCount,omitempty"`    // 累积蝴蝶百搭个数 (基础模式未中奖时清理，免费模式所有免费局数打完进入基础模式时清理)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Jwjzy_BetOrderResponse) Reset() {
	*x = Jwjzy_BetOrderResponse{}
	mi := &file__18926_jwjzy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwjzy_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwjzy_BetOrderResponse) ProtoMessage() {}

func (x *Jwjzy_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file__18926_jwjzy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwjzy_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Jwjzy_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file__18926_jwjzy_proto_rawDescGZIP(), []int{0}
}

func (x *Jwjzy_BetOrderResponse) GetOrderSN() string {
	if x != nil {
		return x.OrderSN
	}
	return ""
}

func (x *Jwjzy_BetOrderResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetBetAmount() float64 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil {
		return x.CurrentWin
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetFreeWin() float64 {
	if x != nil {
		return x.FreeWin
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetTotalWin() float64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetFree() bool {
	if x != nil {
		return x.Free
	}
	return false
}

func (x *Jwjzy_BetOrderResponse) GetReview() int64 {
	if x != nil {
		return x.Review
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetWinInfo() *Jwjzy_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Jwjzy_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Jwjzy_BetOrderResponse) GetScatterCount() int64 {
	if x != nil {
		return x.ScatterCount
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil {
		return x.IsRoundOver
	}
	return false
}

func (x *Jwjzy_BetOrderResponse) GetMulti() int64 {
	if x != nil {
		return x.Multi
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetFreeNum() int64 {
	if x != nil {
		return x.FreeNum
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetFreeTime() int64 {
	if x != nil {
		return x.FreeTime
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Jwjzy_BetOrderResponse) GetIsGameOver() bool {
	if x != nil {
		return x.IsGameOver
	}
	return false
}

func (x *Jwjzy_BetOrderResponse) GetRoundWin() float64 {
	if x != nil {
		return x.RoundWin
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetMulIndex() int64 {
	if x != nil {
		return x.MulIndex
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetBaseMultipliers() []int64 {
	if x != nil {
		return x.BaseMultipliers
	}
	return nil
}

func (x *Jwjzy_BetOrderResponse) GetFreeMultipliers() []int64 {
	if x != nil {
		return x.FreeMultipliers
	}
	return nil
}

func (x *Jwjzy_BetOrderResponse) GetWildEliCount() int64 {
	if x != nil {
		return x.WildEliCount
	}
	return 0
}

func (x *Jwjzy_BetOrderResponse) GetTotalWildEliCount() int64 {
	if x != nil {
		return x.TotalWildEliCount
	}
	return 0
}

// 中奖详情（消除回合内信息）
type Jwjzy_WinInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WinArr          []*Jwjzy_WinArr        `protobuf:"bytes,1,rep,name=winArr,proto3" json:"winArr,omitempty"`                    // 本步各条中奖线的详情
	AddFreeNum      int64                  `protobuf:"varint,2,opt,name=addFreeNum,proto3" json:"addFreeNum,omitempty"`           // 增加的免费次数
	WildEliMultiple int64                  `protobuf:"varint,3,opt,name=wildEliMultiple,proto3" json:"wildEliMultiple,omitempty"` // 蝴蝶百搭倍数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Jwjzy_WinInfo) Reset() {
	*x = Jwjzy_WinInfo{}
	mi := &file__18926_jwjzy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwjzy_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwjzy_WinInfo) ProtoMessage() {}

func (x *Jwjzy_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file__18926_jwjzy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwjzy_WinInfo.ProtoReflect.Descriptor instead.
func (*Jwjzy_WinInfo) Descriptor() ([]byte, []int) {
	return file__18926_jwjzy_proto_rawDescGZIP(), []int{1}
}

func (x *Jwjzy_WinInfo) GetWinArr() []*Jwjzy_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Jwjzy_WinInfo) GetAddFreeNum() int64 {
	if x != nil {
		return x.AddFreeNum
	}
	return 0
}

func (x *Jwjzy_WinInfo) GetWildEliMultiple() int64 {
	if x != nil {
		return x.WildEliMultiple
	}
	return 0
}

// 单条中奖线详情
type Jwjzy_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       int64                  `protobuf:"varint,1,opt,name=roadNum,proto3" json:"roadNum,omitempty"` // 支付线编号 0~19
	Odds          int64                  `protobuf:"varint,2,opt,name=odds,proto3" json:"odds,omitempty"`       // 基础赔率 来自 pay_table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwjzy_WinArr) Reset() {
	*x = Jwjzy_WinArr{}
	mi := &file__18926_jwjzy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwjzy_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwjzy_WinArr) ProtoMessage() {}

func (x *Jwjzy_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file__18926_jwjzy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwjzy_WinArr.ProtoReflect.Descriptor instead.
func (*Jwjzy_WinArr) Descriptor() ([]byte, []int) {
	return file__18926_jwjzy_proto_rawDescGZIP(), []int{2}
}

func (x *Jwjzy_WinArr) GetRoadNum() int64 {
	if x != nil {
		return x.RoadNum
	}
	return 0
}

func (x *Jwjzy_WinArr) GetOdds() int64 {
	if x != nil {
		return x.Odds
	}
	return 0
}

var File__18926_jwjzy_proto protoreflect.FileDescriptor

const file__18926_jwjzy_proto_rawDesc = "" +
	"\n" +
	"\x1118926/jwjzy.proto\x12\x05jwjzy\"\xf2\x05\n" +
	"\x16jwjzy_BetOrderResponse\x12\x18\n" +
	"\aorderSN\x18\x01 \x01(\tR\aorderSN\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1c\n" +
	"\tbetAmount\x18\x03 \x01(\x01R\tbetAmount\x12\x1e\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01R\n" +
	"currentWin\x12\x18\n" +
	"\afreeWin\x18\x05 \x01(\x01R\afreeWin\x12\x1a\n" +
	"\btotalWin\x18\x06 \x01(\x01R\btotalWin\x12\x12\n" +
	"\x04free\x18\a \x01(\bR\x04free\x12\x16\n" +
	"\x06review\x18\b \x01(\x03R\x06review\x12.\n" +
	"\awinInfo\x18\t \x01(\v2\x14.jwjzy.jwjzy_WinInfoR\awinInfo\x12\x14\n" +
	"\x05cards\x18\n" +
	" \x03(\x03R\x05cards\x12\"\n" +
	"\fscatterCount\x18\v \x01(\x03R\fscatterCount\x12 \n" +
	"\visRoundOver\x18\f \x01(\bR\visRoundOver\x12\x14\n" +
	"\x05multi\x18\r \x01(\x03R\x05multi\x12\x14\n" +
	"\x05state\x18\x0e \x01(\x03R\x05state\x12\x18\n" +
	"\afreeNum\x18\x0f \x01(\x03R\afreeNum\x12\x1a\n" +
	"\bfreeTime\x18\x10 \x01(\x03R\bfreeTime\x12\x18\n" +
	"\awinGrid\x18\x11 \x03(\x03R\awinGrid\x12\x1e\n" +
	"\n" +
	"isGameOver\x18\x12 \x01(\bR\n" +
	"isGameOver\x12\x1a\n" +
	"\broundWin\x18\x13 \x01(\x01R\broundWin\x12\x1a\n" +
	"\bmulIndex\x18\x14 \x01(\x03R\bmulIndex\x12(\n" +
	"\x0fbaseMultipliers\x18\x15 \x03(\x03R\x0fbaseMultipliers\x12(\n" +
	"\x0ffreeMultipliers\x18\x16 \x03(\x03R\x0ffreeMultipliers\x12\"\n" +
	"\fwildEliCount\x18\x17 \x01(\x03R\fwildEliCount\x12,\n" +
	"\x11totalWildEliCount\x18\x18 \x01(\x03R\x11totalWildEliCount\"\x86\x01\n" +
	"\rjwjzy_WinInfo\x12+\n" +
	"\x06winArr\x18\x01 \x03(\v2\x13.jwjzy.jwjzy_WinArrR\x06winArr\x12\x1e\n" +
	"\n" +
	"addFreeNum\x18\x02 \x01(\x03R\n" +
	"addFreeNum\x12(\n" +
	"\x0fwildEliMultiple\x18\x03 \x01(\x03R\x0fwildEliMultiple\"<\n" +
	"\fjwjzy_WinArr\x12\x18\n" +
	"\aroadNum\x18\x01 \x01(\x03R\aroadNum\x12\x12\n" +
	"\x04odds\x18\x02 \x01(\x03R\x04oddsB\x1bZ\x19egame-grpc/game/common/pbb\x06proto3"

var (
	file__18926_jwjzy_proto_rawDescOnce sync.Once
	file__18926_jwjzy_proto_rawDescData []byte
)

func file__18926_jwjzy_proto_rawDescGZIP() []byte {
	file__18926_jwjzy_proto_rawDescOnce.Do(func() {
		file__18926_jwjzy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__18926_jwjzy_proto_rawDesc), len(file__18926_jwjzy_proto_rawDesc)))
	})
	return file__18926_jwjzy_proto_rawDescData
}

var file__18926_jwjzy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file__18926_jwjzy_proto_goTypes = []any{
	(*Jwjzy_BetOrderResponse)(nil), // 0: jwjzy.jwjzy_BetOrderResponse
	(*Jwjzy_WinInfo)(nil),          // 1: jwjzy.jwjzy_WinInfo
	(*Jwjzy_WinArr)(nil),           // 2: jwjzy.jwjzy_WinArr
}
var file__18926_jwjzy_proto_depIdxs = []int32{
	1, // 0: jwjzy.jwjzy_BetOrderResponse.winInfo:type_name -> jwjzy.jwjzy_WinInfo
	2, // 1: jwjzy.jwjzy_WinInfo.winArr:type_name -> jwjzy.jwjzy_WinArr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file__18926_jwjzy_proto_init() }
func file__18926_jwjzy_proto_init() {
	if File__18926_jwjzy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__18926_jwjzy_proto_rawDesc), len(file__18926_jwjzy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file__18926_jwjzy_proto_goTypes,
		DependencyIndexes: file__18926_jwjzy_proto_depIdxs,
		MessageInfos:      file__18926_jwjzy_proto_msgTypes,
	}.Build()
	File__18926_jwjzy_proto = out.File
	file__18926_jwjzy_proto_goTypes = nil
	file__18926_jwjzy_proto_depIdxs = nil
}
