// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ys.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ys_BetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn"`                       // 订单号
	Balance       *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"`           // 当前余额
	BetAmount     *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount"`       // 本局下注金额
	CurWin        *float64               `protobuf:"fixed64,4,opt,name=curWin,proto3,oneof" json:"curWin"`             // 本步赢分
	FreeWin       *float64               `protobuf:"fixed64,5,opt,name=freeWin,proto3,oneof" json:"freeWin"`           // 免费模式累计赢分
	RoundWin      *float64               `protobuf:"fixed64,7,opt,name=roundWin,proto3,oneof" json:"roundWin"`         // 当前 round 累计赢分
	IsRoundOver   *bool                  `protobuf:"varint,8,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver"`    // 当前 round 是否结束
	IsFree        *bool                  `protobuf:"varint,10,opt,name=isFree,proto3,oneof" json:"isFree"`             // 是否免费模式
	State         *int64                 `protobuf:"varint,11,opt,name=state,proto3,oneof" json:"state"`               // 当前阶段
	FreeNum       *int64                 `protobuf:"varint,12,opt,name=freeNum,proto3,oneof" json:"freeNum"`           // 剩余免费次数
	FreeTime      *int64                 `protobuf:"varint,13,opt,name=freeTime,proto3,oneof" json:"freeTime"`         // 已执行免费次数
	NewFreeTimes  *int64                 `protobuf:"varint,14,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes"` // 本步新增免费次数
	ScatterCount  *int64                 `protobuf:"varint,15,opt,name=scatterCount,proto3,oneof" json:"scatterCount"` // 当前盘面夺宝数量
	SymGrid       []int64                `protobuf:"varint,16,rep,packed,name=symGrid,proto3" json:"symGrid"`          // 当前盘面
	WinGrid       []int64                `protobuf:"varint,17,rep,packed,name=winGrid,proto3" json:"winGrid"`          // 中奖展示网格
	StepMul       *int64                 `protobuf:"varint,18,opt,name=stepMul,proto3,oneof" json:"stepMul"`           // 本步最终倍数
	Limit         *bool                  `protobuf:"varint,19,opt,name=limit,proto3,oneof" json:"limit"`               // 是否触发最大可赢封顶
	WinArr        []*Ys_WinArr           `protobuf:"bytes,20,rep,name=winArr,proto3" json:"winArr"`                    // 本步中奖条目
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ys_BetOrderResponse) Reset() {
	*x = Ys_BetOrderResponse{}
	mi := &file_ys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ys_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ys_BetOrderResponse) ProtoMessage() {}

func (x *Ys_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ys_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Ys_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_ys_proto_rawDescGZIP(), []int{0}
}

func (x *Ys_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Ys_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Ys_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Ys_BetOrderResponse) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetScatterCount() int64 {
	if x != nil && x.ScatterCount != nil {
		return *x.ScatterCount
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetSymGrid() []int64 {
	if x != nil {
		return x.SymGrid
	}
	return nil
}

func (x *Ys_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Ys_BetOrderResponse) GetStepMul() int64 {
	if x != nil && x.StepMul != nil {
		return *x.StepMul
	}
	return 0
}

func (x *Ys_BetOrderResponse) GetLimit() bool {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return false
}

func (x *Ys_BetOrderResponse) GetWinArr() []*Ys_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

type Ys_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *int64                 `protobuf:"varint,1,opt,name=val,proto3,oneof" json:"val"`         // 中奖符号
	RoadNum       *int64                 `protobuf:"varint,2,opt,name=roadNum,proto3,oneof" json:"roadNum"` // 中奖路数（线数积）
	StarNum       *int64                 `protobuf:"varint,3,opt,name=starNum,proto3,oneof" json:"starNum"` // 连续命中列数
	Odds          *int64                 `protobuf:"varint,4,opt,name=odds,proto3,oneof" json:"odds"`       // 赔率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ys_WinArr) Reset() {
	*x = Ys_WinArr{}
	mi := &file_ys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ys_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ys_WinArr) ProtoMessage() {}

func (x *Ys_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_ys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ys_WinArr.ProtoReflect.Descriptor instead.
func (*Ys_WinArr) Descriptor() ([]byte, []int) {
	return file_ys_proto_rawDescGZIP(), []int{1}
}

func (x *Ys_WinArr) GetVal() int64 {
	if x != nil && x.Val != nil {
		return *x.Val
	}
	return 0
}

func (x *Ys_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Ys_WinArr) GetStarNum() int64 {
	if x != nil && x.StarNum != nil {
		return *x.StarNum
	}
	return 0
}

func (x *Ys_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

var File_ys_proto protoreflect.FileDescriptor

const file_ys_proto_rawDesc = "" +
	"\n" +
	"\bys.proto\x12\x02ys\"\x8a\x06\n" +
	"\x13ys_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x04 \x01(\x01H\x03R\x06curWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\x05 \x01(\x01H\x04R\afreeWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\a \x01(\x01H\x05R\broundWin\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\b \x01(\bH\x06R\visRoundOver\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\n" +
	" \x01(\bH\aR\x06isFree\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\v \x01(\x03H\bR\x05state\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\f \x01(\x03H\tR\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\r \x01(\x03H\n" +
	"R\bfreeTime\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\x0e \x01(\x03H\vR\fnewFreeTimes\x88\x01\x01\x12'\n" +
	"\fscatterCount\x18\x0f \x01(\x03H\fR\fscatterCount\x88\x01\x01\x12\x18\n" +
	"\asymGrid\x18\x10 \x03(\x03R\asymGrid\x12\x18\n" +
	"\awinGrid\x18\x11 \x03(\x03R\awinGrid\x12\x1d\n" +
	"\astepMul\x18\x12 \x01(\x03H\rR\astepMul\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x13 \x01(\bH\x0eR\x05limit\x88\x01\x01\x12%\n" +
	"\x06winArr\x18\x14 \x03(\v2\r.ys.ys_WinArrR\x06winArrB\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\t\n" +
	"\a_curWinB\n" +
	"\n" +
	"\b_freeWinB\v\n" +
	"\t_roundWinB\x0e\n" +
	"\f_isRoundOverB\t\n" +
	"\a_isFreeB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\x0f\n" +
	"\r_newFreeTimesB\x0f\n" +
	"\r_scatterCountB\n" +
	"\n" +
	"\b_stepMulB\b\n" +
	"\x06_limit\"\xa2\x01\n" +
	"\tys_WinArr\x12\x15\n" +
	"\x03val\x18\x01 \x01(\x03H\x00R\x03val\x88\x01\x01\x12\x1d\n" +
	"\aroadNum\x18\x02 \x01(\x03H\x01R\aroadNum\x88\x01\x01\x12\x1d\n" +
	"\astarNum\x18\x03 \x01(\x03H\x02R\astarNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x04 \x01(\x03H\x03R\x04odds\x88\x01\x01B\x06\n" +
	"\x04_valB\n" +
	"\n" +
	"\b_roadNumB\n" +
	"\n" +
	"\b_starNumB\a\n" +
	"\x05_oddsB\x17Z\x15egame-grpc/game/ys/pbb\x06proto3"

var (
	file_ys_proto_rawDescOnce sync.Once
	file_ys_proto_rawDescData []byte
)

func file_ys_proto_rawDescGZIP() []byte {
	file_ys_proto_rawDescOnce.Do(func() {
		file_ys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ys_proto_rawDesc), len(file_ys_proto_rawDesc)))
	})
	return file_ys_proto_rawDescData
}

var file_ys_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ys_proto_goTypes = []any{
	(*Ys_BetOrderResponse)(nil), // 0: ys.ys_BetOrderResponse
	(*Ys_WinArr)(nil),           // 1: ys.ys_WinArr
}
var file_ys_proto_depIdxs = []int32{
	1, // 0: ys.ys_BetOrderResponse.winArr:type_name -> ys.ys_WinArr
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ys_proto_init() }
func file_ys_proto_init() {
	if File_ys_proto != nil {
		return
	}
	file_ys_proto_msgTypes[0].OneofWrappers = []any{}
	file_ys_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ys_proto_rawDesc), len(file_ys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ys_proto_goTypes,
		DependencyIndexes: file_ys_proto_depIdxs,
		MessageInfos:      file_ys_proto_msgTypes,
	}.Build()
	File_ys_proto = out.File
	file_ys_proto_goTypes = nil
	file_ys_proto_depIdxs = nil
}
