// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ajtm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ajtm_BetOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrderSN           string                 `protobuf:"bytes,1,opt,name=orderSN,proto3" json:"orderSN,omitempty"`
	Balance           float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	BetAmount         float64                `protobuf:"fixed64,3,opt,name=betAmount,proto3" json:"betAmount,omitempty"`
	CurrentWin        float64                `protobuf:"fixed64,4,opt,name=currentWin,proto3" json:"currentWin,omitempty"`
	FreeWin           float64                `protobuf:"fixed64,5,opt,name=freeWin,proto3" json:"freeWin,omitempty"`
	TotalWin          float64                `protobuf:"fixed64,6,opt,name=totalWin,proto3" json:"totalWin,omitempty"`
	Free              bool                   `protobuf:"varint,7,opt,name=free,proto3" json:"free,omitempty"`
	Review            int64                  `protobuf:"varint,8,opt,name=review,proto3" json:"review,omitempty"`
	WinInfo           *Ajtm_WinInfo          `protobuf:"bytes,9,opt,name=winInfo,proto3" json:"winInfo,omitempty"`
	Cards             []int64                `protobuf:"varint,10,rep,packed,name=cards,proto3" json:"cards,omitempty"`
	ScatterCount      int64                  `protobuf:"varint,11,opt,name=scatterCount,proto3" json:"scatterCount,omitempty"`
	IsRoundOver       bool                   `protobuf:"varint,12,opt,name=isRoundOver,proto3" json:"isRoundOver,omitempty"`
	Multi             int64                  `protobuf:"varint,13,opt,name=multi,proto3" json:"multi,omitempty"`
	State             int64                  `protobuf:"varint,14,opt,name=state,proto3" json:"state,omitempty"`
	FreeNum           int64                  `protobuf:"varint,15,opt,name=freeNum,proto3" json:"freeNum,omitempty"`
	FreeTime          int64                  `protobuf:"varint,16,opt,name=freeTime,proto3" json:"freeTime,omitempty"`
	WinGrid           []int64                `protobuf:"varint,17,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`
	IsGameOver        bool                   `protobuf:"varint,18,opt,name=isGameOver,proto3" json:"isGameOver,omitempty"`
	RoundWin          float64                `protobuf:"fixed64,19,opt,name=roundWin,proto3" json:"roundWin,omitempty"`
	MulIndex          int64                  `protobuf:"varint,20,opt,name=mulIndex,proto3" json:"mulIndex,omitempty"`
	BaseMultipliers   []int64                `protobuf:"varint,21,rep,packed,name=baseMultipliers,proto3" json:"baseMultipliers,omitempty"`
	FreeMultipliers   []int64                `protobuf:"varint,22,rep,packed,name=freeMultipliers,proto3" json:"freeMultipliers,omitempty"`
	WildEliCount      int64                  `protobuf:"varint,23,opt,name=wildEliCount,proto3" json:"wildEliCount,omitempty"`
	TotalWildEliCount int64                  `protobuf:"varint,24,opt,name=totalWildEliCount,proto3" json:"totalWildEliCount,omitempty"`
	LongEvents        []*Ajtm_LongEvent      `protobuf:"bytes,25,rep,name=longEvents,proto3" json:"longEvents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ajtm_BetOrderResponse) Reset() {
	*x = Ajtm_BetOrderResponse{}
	mi := &file_ajtm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ajtm_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ajtm_BetOrderResponse) ProtoMessage() {}

func (x *Ajtm_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ajtm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ajtm_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Ajtm_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_ajtm_proto_rawDescGZIP(), []int{0}
}

func (x *Ajtm_BetOrderResponse) GetOrderSN() string {
	if x != nil {
		return x.OrderSN
	}
	return ""
}

func (x *Ajtm_BetOrderResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetBetAmount() float64 {
	if x != nil {
		return x.BetAmount
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil {
		return x.CurrentWin
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetFreeWin() float64 {
	if x != nil {
		return x.FreeWin
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetTotalWin() float64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetFree() bool {
	if x != nil {
		return x.Free
	}
	return false
}

func (x *Ajtm_BetOrderResponse) GetReview() int64 {
	if x != nil {
		return x.Review
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetWinInfo() *Ajtm_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Ajtm_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Ajtm_BetOrderResponse) GetScatterCount() int64 {
	if x != nil {
		return x.ScatterCount
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil {
		return x.IsRoundOver
	}
	return false
}

func (x *Ajtm_BetOrderResponse) GetMulti() int64 {
	if x != nil {
		return x.Multi
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetFreeNum() int64 {
	if x != nil {
		return x.FreeNum
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetFreeTime() int64 {
	if x != nil {
		return x.FreeTime
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Ajtm_BetOrderResponse) GetIsGameOver() bool {
	if x != nil {
		return x.IsGameOver
	}
	return false
}

func (x *Ajtm_BetOrderResponse) GetRoundWin() float64 {
	if x != nil {
		return x.RoundWin
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetMulIndex() int64 {
	if x != nil {
		return x.MulIndex
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetBaseMultipliers() []int64 {
	if x != nil {
		return x.BaseMultipliers
	}
	return nil
}

func (x *Ajtm_BetOrderResponse) GetFreeMultipliers() []int64 {
	if x != nil {
		return x.FreeMultipliers
	}
	return nil
}

func (x *Ajtm_BetOrderResponse) GetWildEliCount() int64 {
	if x != nil {
		return x.WildEliCount
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetTotalWildEliCount() int64 {
	if x != nil {
		return x.TotalWildEliCount
	}
	return 0
}

func (x *Ajtm_BetOrderResponse) GetLongEvents() []*Ajtm_LongEvent {
	if x != nil {
		return x.LongEvents
	}
	return nil
}

type Ajtm_WinInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WinArr          []*Ajtm_WinArr         `protobuf:"bytes,1,rep,name=winArr,proto3" json:"winArr,omitempty"`
	AddFreeNum      int64                  `protobuf:"varint,2,opt,name=addFreeNum,proto3" json:"addFreeNum,omitempty"`
	WildEliMultiple int64                  `protobuf:"varint,3,opt,name=wildEliMultiple,proto3" json:"wildEliMultiple,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Ajtm_WinInfo) Reset() {
	*x = Ajtm_WinInfo{}
	mi := &file_ajtm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ajtm_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ajtm_WinInfo) ProtoMessage() {}

func (x *Ajtm_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ajtm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ajtm_WinInfo.ProtoReflect.Descriptor instead.
func (*Ajtm_WinInfo) Descriptor() ([]byte, []int) {
	return file_ajtm_proto_rawDescGZIP(), []int{1}
}

func (x *Ajtm_WinInfo) GetWinArr() []*Ajtm_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Ajtm_WinInfo) GetAddFreeNum() int64 {
	if x != nil {
		return x.AddFreeNum
	}
	return 0
}

func (x *Ajtm_WinInfo) GetWildEliMultiple() int64 {
	if x != nil {
		return x.WildEliMultiple
	}
	return 0
}

type Ajtm_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       int64                  `protobuf:"varint,1,opt,name=roadNum,proto3" json:"roadNum,omitempty"`
	Odds          int64                  `protobuf:"varint,2,opt,name=odds,proto3" json:"odds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ajtm_WinArr) Reset() {
	*x = Ajtm_WinArr{}
	mi := &file_ajtm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ajtm_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ajtm_WinArr) ProtoMessage() {}

func (x *Ajtm_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_ajtm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ajtm_WinArr.ProtoReflect.Descriptor instead.
func (*Ajtm_WinArr) Descriptor() ([]byte, []int) {
	return file_ajtm_proto_rawDescGZIP(), []int{2}
}

func (x *Ajtm_WinArr) GetRoadNum() int64 {
	if x != nil {
		return x.RoadNum
	}
	return 0
}

func (x *Ajtm_WinArr) GetOdds() int64 {
	if x != nil {
		return x.Odds
	}
	return 0
}

type Ajtm_LongEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Col           int64                  `protobuf:"varint,1,opt,name=col,proto3" json:"col,omitempty"`
	HeadRow       int64                  `protobuf:"varint,2,opt,name=headRow,proto3" json:"headRow,omitempty"`
	TailRow       int64                  `protobuf:"varint,3,opt,name=tailRow,proto3" json:"tailRow,omitempty"`
	OldSymbol     int64                  `protobuf:"varint,4,opt,name=oldSymbol,proto3" json:"oldSymbol,omitempty"`
	NewSymbol     int64                  `protobuf:"varint,5,opt,name=newSymbol,proto3" json:"newSymbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ajtm_LongEvent) Reset() {
	*x = Ajtm_LongEvent{}
	mi := &file_ajtm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ajtm_LongEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ajtm_LongEvent) ProtoMessage() {}

func (x *Ajtm_LongEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ajtm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ajtm_LongEvent.ProtoReflect.Descriptor instead.
func (*Ajtm_LongEvent) Descriptor() ([]byte, []int) {
	return file_ajtm_proto_rawDescGZIP(), []int{3}
}

func (x *Ajtm_LongEvent) GetCol() int64 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *Ajtm_LongEvent) GetHeadRow() int64 {
	if x != nil {
		return x.HeadRow
	}
	return 0
}

func (x *Ajtm_LongEvent) GetTailRow() int64 {
	if x != nil {
		return x.TailRow
	}
	return 0
}

func (x *Ajtm_LongEvent) GetOldSymbol() int64 {
	if x != nil {
		return x.OldSymbol
	}
	return 0
}

func (x *Ajtm_LongEvent) GetNewSymbol() int64 {
	if x != nil {
		return x.NewSymbol
	}
	return 0
}

var File_ajtm_proto protoreflect.FileDescriptor

const file_ajtm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ajtm.proto\x12\x04ajtm\"\xa5\x06\n" +
	"\x15ajtm_BetOrderResponse\x12\x18\n" +
	"\aorderSN\x18\x01 \x01(\tR\aorderSN\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x1c\n" +
	"\tbetAmount\x18\x03 \x01(\x01R\tbetAmount\x12\x1e\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01R\n" +
	"currentWin\x12\x18\n" +
	"\afreeWin\x18\x05 \x01(\x01R\afreeWin\x12\x1a\n" +
	"\btotalWin\x18\x06 \x01(\x01R\btotalWin\x12\x12\n" +
	"\x04free\x18\a \x01(\bR\x04free\x12\x16\n" +
	"\x06review\x18\b \x01(\x03R\x06review\x12,\n" +
	"\awinInfo\x18\t \x01(\v2\x12.ajtm.ajtm_WinInfoR\awinInfo\x12\x14\n" +
	"\x05cards\x18\n" +
	" \x03(\x03R\x05cards\x12\"\n" +
	"\fscatterCount\x18\v \x01(\x03R\fscatterCount\x12 \n" +
	"\visRoundOver\x18\f \x01(\bR\visRoundOver\x12\x14\n" +
	"\x05multi\x18\r \x01(\x03R\x05multi\x12\x14\n" +
	"\x05state\x18\x0e \x01(\x03R\x05state\x12\x18\n" +
	"\afreeNum\x18\x0f \x01(\x03R\afreeNum\x12\x1a\n" +
	"\bfreeTime\x18\x10 \x01(\x03R\bfreeTime\x12\x18\n" +
	"\awinGrid\x18\x11 \x03(\x03R\awinGrid\x12\x1e\n" +
	"\n" +
	"isGameOver\x18\x12 \x01(\bR\n" +
	"isGameOver\x12\x1a\n" +
	"\broundWin\x18\x13 \x01(\x01R\broundWin\x12\x1a\n" +
	"\bmulIndex\x18\x14 \x01(\x03R\bmulIndex\x12(\n" +
	"\x0fbaseMultipliers\x18\x15 \x03(\x03R\x0fbaseMultipliers\x12(\n" +
	"\x0ffreeMultipliers\x18\x16 \x03(\x03R\x0ffreeMultipliers\x12\"\n" +
	"\fwildEliCount\x18\x17 \x01(\x03R\fwildEliCount\x12,\n" +
	"\x11totalWildEliCount\x18\x18 \x01(\x03R\x11totalWildEliCount\x124\n" +
	"\n" +
	"longEvents\x18\x19 \x03(\v2\x14.ajtm.ajtm_LongEventR\n" +
	"longEvents\"\x83\x01\n" +
	"\fajtm_WinInfo\x12)\n" +
	"\x06winArr\x18\x01 \x03(\v2\x11.ajtm.ajtm_WinArrR\x06winArr\x12\x1e\n" +
	"\n" +
	"addFreeNum\x18\x02 \x01(\x03R\n" +
	"addFreeNum\x12(\n" +
	"\x0fwildEliMultiple\x18\x03 \x01(\x03R\x0fwildEliMultiple\";\n" +
	"\vajtm_WinArr\x12\x18\n" +
	"\aroadNum\x18\x01 \x01(\x03R\aroadNum\x12\x12\n" +
	"\x04odds\x18\x02 \x01(\x03R\x04odds\"\x92\x01\n" +
	"\x0eajtm_LongEvent\x12\x10\n" +
	"\x03col\x18\x01 \x01(\x03R\x03col\x12\x18\n" +
	"\aheadRow\x18\x02 \x01(\x03R\aheadRow\x12\x18\n" +
	"\atailRow\x18\x03 \x01(\x03R\atailRow\x12\x1c\n" +
	"\toldSymbol\x18\x04 \x01(\x03R\toldSymbol\x12\x1c\n" +
	"\tnewSymbol\x18\x05 \x01(\x03R\tnewSymbolB\x1bZ\x19egame-grpc/game/common/pbb\x06proto3"

var (
	file_ajtm_proto_rawDescOnce sync.Once
	file_ajtm_proto_rawDescData []byte
)

func file_ajtm_proto_rawDescGZIP() []byte {
	file_ajtm_proto_rawDescOnce.Do(func() {
		file_ajtm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ajtm_proto_rawDesc), len(file_ajtm_proto_rawDesc)))
	})
	return file_ajtm_proto_rawDescData
}

var file_ajtm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ajtm_proto_goTypes = []any{
	(*Ajtm_BetOrderResponse)(nil), // 0: ajtm.ajtm_BetOrderResponse
	(*Ajtm_WinInfo)(nil),          // 1: ajtm.ajtm_WinInfo
	(*Ajtm_WinArr)(nil),           // 2: ajtm.ajtm_WinArr
	(*Ajtm_LongEvent)(nil),        // 3: ajtm.ajtm_LongEvent
}
var file_ajtm_proto_depIdxs = []int32{
	1, // 0: ajtm.ajtm_BetOrderResponse.winInfo:type_name -> ajtm.ajtm_WinInfo
	3, // 1: ajtm.ajtm_BetOrderResponse.longEvents:type_name -> ajtm.ajtm_LongEvent
	2, // 2: ajtm.ajtm_WinInfo.winArr:type_name -> ajtm.ajtm_WinArr
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ajtm_proto_init() }
func file_ajtm_proto_init() {
	if File_ajtm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ajtm_proto_rawDesc), len(file_ajtm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ajtm_proto_goTypes,
		DependencyIndexes: file_ajtm_proto_depIdxs,
		MessageInfos:      file_ajtm_proto_msgTypes,
	}.Build()
	File_ajtm_proto = out.File
	file_ajtm_proto_goTypes = nil
	file_ajtm_proto_depIdxs = nil
}
