// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ycj.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ycj_BetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn,omitempty"`                       // 订单号
	Balance       *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`           // 当前余额
	BaseBet       *float64               `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet,omitempty"`           // 基础下注
	Multiplier    *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"`      // 下注倍数
	BetAmount     *float64               `protobuf:"fixed64,5,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`       // 实际投注金额（baseBet × multiplier）
	CurWin        *float64               `protobuf:"fixed64,6,opt,name=curWin,proto3,oneof" json:"curWin,omitempty"`             // 本步结算赢取金额
	FreeWin       *float64               `protobuf:"fixed64,7,opt,name=freeWin,proto3,oneof" json:"freeWin,omitempty"`           // 免费游戏中累计赢取
	TotalWin      *float64               `protobuf:"fixed64,8,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`         // 本回合总赢取
	IsFree        *bool                  `protobuf:"varint,9,opt,name=isFree,proto3,oneof" json:"isFree,omitempty"`              // 是否处于免费模式
	Review        *int64                 `protobuf:"varint,10,opt,name=review,proto3,oneof" json:"review,omitempty"`             // 复盘标志
	IsRoundOver   *bool                  `protobuf:"varint,11,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver,omitempty"`   // 是否结束
	FreeNum       *int64                 `protobuf:"varint,12,opt,name=freeNum,proto3,oneof" json:"freeNum,omitempty"`           // 剩余免费次数
	FreeTime      *int64                 `protobuf:"varint,13,opt,name=freeTime,proto3,oneof" json:"freeTime,omitempty"`         // 已使用免费次数
	NewFreeTimes  *int64                 `protobuf:"varint,14,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes,omitempty"` // 本步新增的免费旋转次数
	SymGrid       []int64                `protobuf:"varint,15,rep,packed,name=symGrid,proto3" json:"symGrid,omitempty"`          // 牌面
	Next          *bool                  `protobuf:"varint,16,opt,name=next,proto3,oneof" json:"next,omitempty"`                 // 是否进入下一状态/下一局 (推展/重转补判未完成）
	StepMul       *float64               `protobuf:"fixed64,17,opt,name=stepMul,proto3,oneof" json:"stepMul,omitempty"`          // 返奖倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ycj_BetOrderResponse) Reset() {
	*x = Ycj_BetOrderResponse{}
	mi := &file_ycj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ycj_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ycj_BetOrderResponse) ProtoMessage() {}

func (x *Ycj_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ycj_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Ycj_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_ycj_proto_rawDescGZIP(), []int{0}
}

func (x *Ycj_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Ycj_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Ycj_BetOrderResponse) GetSymGrid() []int64 {
	if x != nil {
		return x.SymGrid
	}
	return nil
}

func (x *Ycj_BetOrderResponse) GetNext() bool {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return false
}

func (x *Ycj_BetOrderResponse) GetStepMul() float64 {
	if x != nil && x.StepMul != nil {
		return *x.StepMul
	}
	return 0
}

var File_ycj_proto protoreflect.FileDescriptor

const file_ycj_proto_rawDesc = "" +
	"\n" +
	"\tycj.proto\x12\x03ycj\"\xef\x05\n" +
	"\x14Ycj_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x05 \x01(\x01H\x04R\tbetAmount\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x06 \x01(\x01H\x05R\x06curWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\a \x01(\x01H\x06R\afreeWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\b \x01(\x01H\aR\btotalWin\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\t \x01(\bH\bR\x06isFree\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\n" +
	" \x01(\x03H\tR\x06review\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\v \x01(\bH\n" +
	"R\visRoundOver\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\f \x01(\x03H\vR\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\r \x01(\x03H\fR\bfreeTime\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\x0e \x01(\x03H\rR\fnewFreeTimes\x88\x01\x01\x12\x18\n" +
	"\asymGrid\x18\x0f \x03(\x03R\asymGrid\x12\x17\n" +
	"\x04next\x18\x10 \x01(\bH\x0eR\x04next\x88\x01\x01\x12\x1d\n" +
	"\astepMul\x18\x11 \x01(\x01H\x0fR\astepMul\x88\x01\x01B\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\r\n" +
	"\v_multiplierB\f\n" +
	"\n" +
	"_betAmountB\t\n" +
	"\a_curWinB\n" +
	"\n" +
	"\b_freeWinB\v\n" +
	"\t_totalWinB\t\n" +
	"\a_isFreeB\t\n" +
	"\a_reviewB\x0e\n" +
	"\f_isRoundOverB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\x0f\n" +
	"\r_newFreeTimesB\a\n" +
	"\x05_nextB\n" +
	"\n" +
	"\b_stepMulB\x18Z\x16egame-grpc/game/ycj/pbb\x06proto3"

var (
	file_ycj_proto_rawDescOnce sync.Once
	file_ycj_proto_rawDescData []byte
)

func file_ycj_proto_rawDescGZIP() []byte {
	file_ycj_proto_rawDescOnce.Do(func() {
		file_ycj_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ycj_proto_rawDesc), len(file_ycj_proto_rawDesc)))
	})
	return file_ycj_proto_rawDescData
}

var file_ycj_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ycj_proto_goTypes = []any{
	(*Ycj_BetOrderResponse)(nil), // 0: ycj.Ycj_BetOrderResponse
}
var file_ycj_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ycj_proto_init() }
func file_ycj_proto_init() {
	if File_ycj_proto != nil {
		return
	}
	file_ycj_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ycj_proto_rawDesc), len(file_ycj_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ycj_proto_goTypes,
		DependencyIndexes: file_ycj_proto_depIdxs,
		MessageInfos:      file_ycj_proto_msgTypes,
	}.Build()
	File_ycj_proto = out.File
	file_ycj_proto_goTypes = nil
	file_ycj_proto_depIdxs = nil
}
