// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ycpd.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 中奖详情响应
type Ycpd_BetOrderResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sn                 *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn"`                                   // 订单号
	Balance            *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"`                       // 当前余额
	BaseBet            *float64               `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet"`                       // 基础下注
	BetAmount          *float64               `protobuf:"fixed64,4,opt,name=betAmount,proto3,oneof" json:"betAmount"`                   // 实际投注金额（baseBet × multiplier）
	Multiplier         *int64                 `protobuf:"varint,5,opt,name=multiplier,proto3,oneof" json:"multiplier"`                  // 下注倍数
	CurWin             *float64               `protobuf:"fixed64,6,opt,name=curWin,proto3,oneof" json:"curWin"`                         // step：本次 betOrder 赢分
	RoundWin           *float64               `protobuf:"fixed64,7,opt,name=roundWin,proto3,oneof" json:"roundWin"`                     // round：本回合累计赢（消除类多步累计）
	TotalWin           *float64               `protobuf:"fixed64,8,opt,name=totalWin,proto3,oneof" json:"totalWin"`                     // spin：本 spin 总赢（含免费触发轮）
	FreeTotalWin       *float64               `protobuf:"fixed64,9,opt,name=freeTotalWin,proto3,oneof" json:"freeTotalWin"`             // 免费局阶段累计总赢（不含触发轮）
	IsRoundOver        *bool                  `protobuf:"varint,10,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver"`               // 本 round 是否结束
	IsSpinOver         *bool                  `protobuf:"varint,11,opt,name=isSpinOver,proto3,oneof" json:"isSpinOver"`                 // 本 spin 是否结束
	IsFree             *bool                  `protobuf:"varint,12,opt,name=isFree,proto3,oneof" json:"isFree"`                         // 当前是否处于免费游戏
	NewFreeTimes       *int64                 `protobuf:"varint,13,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes"`             // 新增免费次数
	RemainingFreeTimes *int64                 `protobuf:"varint,14,opt,name=remainingFreeTimes,proto3,oneof" json:"remainingFreeTimes"` // 剩余免费次数
	TotalFreeTimes     *int64                 `protobuf:"varint,15,opt,name=totalFreeTimes,proto3,oneof" json:"totalFreeTimes"`         // 总免费局数
	SymGrid            []int64                `protobuf:"varint,16,rep,packed,name=symGrid,proto3" json:"symGrid"`                      // 牌面
	State              *int64                 `protobuf:"varint,17,opt,name=state,proto3,oneof" json:"state"`                           // 状态
	WinArr             []*Ycpd_WinArr         `protobuf:"bytes,18,rep,name=winArr,proto3" json:"winArr"`                                // 中奖详细信息
	WinGird            []int64                `protobuf:"varint,19,rep,packed,name=winGird,proto3" json:"winGird"`                      // 中奖网格
	LineMul            *int64                 `protobuf:"varint,20,opt,name=lineMul,proto3,oneof" json:"lineMul"`                       // 线中奖倍数
	StepMul            *int64                 `protobuf:"varint,21,opt,name=stepMul,proto3,oneof" json:"stepMul"`                       // 总倍数
	GameMul            *int64                 `protobuf:"varint,22,opt,name=gameMul,proto3,oneof" json:"gameMul"`                       // 倍数
	RemoveMul          []int64                `protobuf:"varint,23,rep,packed,name=RemoveMul,proto3" json:"RemoveMul"`                  // 累计第2.3.4倍数
	CurGameMul         []int64                `protobuf:"varint,24,rep,packed,name=curGameMul,proto3" json:"curGameMul"`                // 当前第2.3.4倍数
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ycpd_BetOrderResponse) Reset() {
	*x = Ycpd_BetOrderResponse{}
	mi := &file_ycpd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ycpd_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ycpd_BetOrderResponse) ProtoMessage() {}

func (x *Ycpd_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycpd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ycpd_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Ycpd_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_ycpd_proto_rawDescGZIP(), []int{0}
}

func (x *Ycpd_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Ycpd_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetFreeTotalWin() float64 {
	if x != nil && x.FreeTotalWin != nil {
		return *x.FreeTotalWin
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Ycpd_BetOrderResponse) GetIsSpinOver() bool {
	if x != nil && x.IsSpinOver != nil {
		return *x.IsSpinOver
	}
	return false
}

func (x *Ycpd_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Ycpd_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetRemainingFreeTimes() int64 {
	if x != nil && x.RemainingFreeTimes != nil {
		return *x.RemainingFreeTimes
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetTotalFreeTimes() int64 {
	if x != nil && x.TotalFreeTimes != nil {
		return *x.TotalFreeTimes
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetSymGrid() []int64 {
	if x != nil {
		return x.SymGrid
	}
	return nil
}

func (x *Ycpd_BetOrderResponse) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetWinArr() []*Ycpd_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Ycpd_BetOrderResponse) GetWinGird() []int64 {
	if x != nil {
		return x.WinGird
	}
	return nil
}

func (x *Ycpd_BetOrderResponse) GetLineMul() int64 {
	if x != nil && x.LineMul != nil {
		return *x.LineMul
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetStepMul() int64 {
	if x != nil && x.StepMul != nil {
		return *x.StepMul
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetGameMul() int64 {
	if x != nil && x.GameMul != nil {
		return *x.GameMul
	}
	return 0
}

func (x *Ycpd_BetOrderResponse) GetRemoveMul() []int64 {
	if x != nil {
		return x.RemoveMul
	}
	return nil
}

func (x *Ycpd_BetOrderResponse) GetCurGameMul() []int64 {
	if x != nil {
		return x.CurGameMul
	}
	return nil
}

type Ycpd_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sym           *int64                 `protobuf:"varint,1,opt,name=sym,proto3,oneof" json:"sym"`         // 中奖符号
	Scnt          *int64                 `protobuf:"varint,2,opt,name=scnt,proto3,oneof" json:"scnt"`       // 数量
	Lcnt          *int64                 `protobuf:"varint,3,opt,name=lcnt,proto3,oneof" json:"lcnt"`       // 中奖路
	BaseMu        *int64                 `protobuf:"varint,4,opt,name=baseMu,proto3,oneof" json:"baseMu"`   // 线赔付倍数
	TotalMu       *int64                 `protobuf:"varint,5,opt,name=totalMu,proto3,oneof" json:"totalMu"` // 总倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ycpd_WinArr) Reset() {
	*x = Ycpd_WinArr{}
	mi := &file_ycpd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ycpd_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ycpd_WinArr) ProtoMessage() {}

func (x *Ycpd_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_ycpd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ycpd_WinArr.ProtoReflect.Descriptor instead.
func (*Ycpd_WinArr) Descriptor() ([]byte, []int) {
	return file_ycpd_proto_rawDescGZIP(), []int{1}
}

func (x *Ycpd_WinArr) GetSym() int64 {
	if x != nil && x.Sym != nil {
		return *x.Sym
	}
	return 0
}

func (x *Ycpd_WinArr) GetScnt() int64 {
	if x != nil && x.Scnt != nil {
		return *x.Scnt
	}
	return 0
}

func (x *Ycpd_WinArr) GetLcnt() int64 {
	if x != nil && x.Lcnt != nil {
		return *x.Lcnt
	}
	return 0
}

func (x *Ycpd_WinArr) GetBaseMu() int64 {
	if x != nil && x.BaseMu != nil {
		return *x.BaseMu
	}
	return 0
}

func (x *Ycpd_WinArr) GetTotalMu() int64 {
	if x != nil && x.TotalMu != nil {
		return *x.TotalMu
	}
	return 0
}

var File_ycpd_proto protoreflect.FileDescriptor

const file_ycpd_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ycpd.proto\x12\x04ycpd\"\xc8\b\n" +
	"\x15ycpd_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x04 \x01(\x01H\x03R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x05 \x01(\x03H\x04R\n" +
	"multiplier\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x06 \x01(\x01H\x05R\x06curWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\a \x01(\x01H\x06R\broundWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\b \x01(\x01H\aR\btotalWin\x88\x01\x01\x12'\n" +
	"\ffreeTotalWin\x18\t \x01(\x01H\bR\ffreeTotalWin\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\n" +
	" \x01(\bH\tR\visRoundOver\x88\x01\x01\x12#\n" +
	"\n" +
	"isSpinOver\x18\v \x01(\bH\n" +
	"R\n" +
	"isSpinOver\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\f \x01(\bH\vR\x06isFree\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\r \x01(\x03H\fR\fnewFreeTimes\x88\x01\x01\x123\n" +
	"\x12remainingFreeTimes\x18\x0e \x01(\x03H\rR\x12remainingFreeTimes\x88\x01\x01\x12+\n" +
	"\x0etotalFreeTimes\x18\x0f \x01(\x03H\x0eR\x0etotalFreeTimes\x88\x01\x01\x12\x18\n" +
	"\asymGrid\x18\x10 \x03(\x03R\asymGrid\x12\x19\n" +
	"\x05state\x18\x11 \x01(\x03H\x0fR\x05state\x88\x01\x01\x12)\n" +
	"\x06winArr\x18\x12 \x03(\v2\x11.ycpd.ycpd_WinArrR\x06winArr\x12\x18\n" +
	"\awinGird\x18\x13 \x03(\x03R\awinGird\x12\x1d\n" +
	"\alineMul\x18\x14 \x01(\x03H\x10R\alineMul\x88\x01\x01\x12\x1d\n" +
	"\astepMul\x18\x15 \x01(\x03H\x11R\astepMul\x88\x01\x01\x12\x1d\n" +
	"\agameMul\x18\x16 \x01(\x03H\x12R\agameMul\x88\x01\x01\x12\x1c\n" +
	"\tRemoveMul\x18\x17 \x03(\x03R\tRemoveMul\x12\x1e\n" +
	"\n" +
	"curGameMul\x18\x18 \x03(\x03R\n" +
	"curGameMulB\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_multiplierB\t\n" +
	"\a_curWinB\v\n" +
	"\t_roundWinB\v\n" +
	"\t_totalWinB\x0f\n" +
	"\r_freeTotalWinB\x0e\n" +
	"\f_isRoundOverB\r\n" +
	"\v_isSpinOverB\t\n" +
	"\a_isFreeB\x0f\n" +
	"\r_newFreeTimesB\x15\n" +
	"\x13_remainingFreeTimesB\x11\n" +
	"\x0f_totalFreeTimesB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_lineMulB\n" +
	"\n" +
	"\b_stepMulB\n" +
	"\n" +
	"\b_gameMul\"\xc3\x01\n" +
	"\vycpd_WinArr\x12\x15\n" +
	"\x03sym\x18\x01 \x01(\x03H\x00R\x03sym\x88\x01\x01\x12\x17\n" +
	"\x04scnt\x18\x02 \x01(\x03H\x01R\x04scnt\x88\x01\x01\x12\x17\n" +
	"\x04lcnt\x18\x03 \x01(\x03H\x02R\x04lcnt\x88\x01\x01\x12\x1b\n" +
	"\x06baseMu\x18\x04 \x01(\x03H\x03R\x06baseMu\x88\x01\x01\x12\x1d\n" +
	"\atotalMu\x18\x05 \x01(\x03H\x04R\atotalMu\x88\x01\x01B\x06\n" +
	"\x04_symB\a\n" +
	"\x05_scntB\a\n" +
	"\x05_lcntB\t\n" +
	"\a_baseMuB\n" +
	"\n" +
	"\b_totalMuB\aZ\x05./;pbb\x06proto3"

var (
	file_ycpd_proto_rawDescOnce sync.Once
	file_ycpd_proto_rawDescData []byte
)

func file_ycpd_proto_rawDescGZIP() []byte {
	file_ycpd_proto_rawDescOnce.Do(func() {
		file_ycpd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ycpd_proto_rawDesc), len(file_ycpd_proto_rawDesc)))
	})
	return file_ycpd_proto_rawDescData
}

var file_ycpd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ycpd_proto_goTypes = []any{
	(*Ycpd_BetOrderResponse)(nil), // 0: ycpd.ycpd_BetOrderResponse
	(*Ycpd_WinArr)(nil),           // 1: ycpd.ycpd_WinArr
}
var file_ycpd_proto_depIdxs = []int32{
	1, // 0: ycpd.ycpd_BetOrderResponse.winArr:type_name -> ycpd.ycpd_WinArr
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ycpd_proto_init() }
func file_ycpd_proto_init() {
	if File_ycpd_proto != nil {
		return
	}
	file_ycpd_proto_msgTypes[0].OneofWrappers = []any{}
	file_ycpd_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ycpd_proto_rawDesc), len(file_ycpd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ycpd_proto_goTypes,
		DependencyIndexes: file_ycpd_proto_depIdxs,
		MessageInfos:      file_ycpd_proto_msgTypes,
	}.Build()
	File_ycpd_proto = out.File
	file_ycpd_proto_goTypes = nil
	file_ycpd_proto_depIdxs = nil
}
