// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: clzw.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Clzw_BetOrderResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sn                 *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn,omitempty"`                                   // 订单号
	Balance            *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`                       // 当前余额
	BaseBet            *float64               `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet,omitempty"`                       // 基础下注
	Multiplier         *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"`                  // 下注倍数
	BetAmount          *float64               `protobuf:"fixed64,5,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`                   // 本局下注金额
	CurWin             *float64               `protobuf:"fixed64,6,opt,name=curWin,proto3,oneof" json:"curWin,omitempty"`                         // step：本次 betOrder 赢分
	RoundWin           *float64               `protobuf:"fixed64,7,opt,name=roundWin,proto3,oneof" json:"roundWin,omitempty"`                     // round：本回合累计赢（消除类多步累计）
	TotalWin           *float64               `protobuf:"fixed64,8,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`                     // spin：本 spin 总赢（含免费触发轮）
	FreeTotalWin       *float64               `protobuf:"fixed64,9,opt,name=freeTotalWin,proto3,oneof" json:"freeTotalWin,omitempty"`             // 免费局阶段累计总赢（不含触发轮）
	IsRoundOver        *bool                  `protobuf:"varint,10,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver,omitempty"`               // 本 round 是否结束
	IsSpinOver         *bool                  `protobuf:"varint,11,opt,name=isSpinOver,proto3,oneof" json:"isSpinOver,omitempty"`                 // 本 spin 是否结束
	IsFree             *bool                  `protobuf:"varint,12,opt,name=isFree,proto3,oneof" json:"isFree,omitempty"`                         // 当前是否处于免费游戏
	NewFreeTimes       *int64                 `protobuf:"varint,13,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes,omitempty"`             // 新增免费次数
	RemainingFreeTimes *int64                 `protobuf:"varint,14,opt,name=remainingFreeTimes,proto3,oneof" json:"remainingFreeTimes,omitempty"` // 剩余免费次数
	TotalFreeTimes     *int64                 `protobuf:"varint,15,opt,name=totalFreeTimes,proto3,oneof" json:"totalFreeTimes,omitempty"`         // 总免费局数
	SymGrid            []int64                `protobuf:"varint,16,rep,packed,name=symGrid,proto3" json:"symGrid,omitempty"`                      // 当前盘面
	WinGrid            []int64                `protobuf:"varint,17,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`                      // 中奖展示网格
	WinArr             []*Clzw_WinArr         `protobuf:"bytes,18,rep,name=winArr,proto3" json:"winArr,omitempty"`                                // 本步中奖条目
	StepMul            *int64                 `protobuf:"varint,19,opt,name=stepMul,proto3,oneof" json:"stepMul,omitempty"`                       // 本步最终倍数
	Limit              *bool                  `protobuf:"varint,20,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                           // 是否触发最大可赢封顶
	ScatterCount       *int64                 `protobuf:"varint,21,opt,name=scatterCount,proto3,oneof" json:"scatterCount,omitempty"`             // 当前盘面夺宝数量
	IsPurchase         *bool                  `protobuf:"varint,22,opt,name=isPurchase,proto3,oneof" json:"isPurchase,omitempty"`                 // 是否处于购买
	RoundStep          *int64                 `protobuf:"varint,23,opt,name=roundStep,proto3,oneof" json:"roundStep,omitempty"`                   // 连续消除步数 0开始
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Clzw_BetOrderResponse) Reset() {
	*x = Clzw_BetOrderResponse{}
	mi := &file_clzw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clzw_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clzw_BetOrderResponse) ProtoMessage() {}

func (x *Clzw_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clzw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clzw_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Clzw_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_clzw_proto_rawDescGZIP(), []int{0}
}

func (x *Clzw_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Clzw_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetFreeTotalWin() float64 {
	if x != nil && x.FreeTotalWin != nil {
		return *x.FreeTotalWin
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Clzw_BetOrderResponse) GetIsSpinOver() bool {
	if x != nil && x.IsSpinOver != nil {
		return *x.IsSpinOver
	}
	return false
}

func (x *Clzw_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Clzw_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetRemainingFreeTimes() int64 {
	if x != nil && x.RemainingFreeTimes != nil {
		return *x.RemainingFreeTimes
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetTotalFreeTimes() int64 {
	if x != nil && x.TotalFreeTimes != nil {
		return *x.TotalFreeTimes
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetSymGrid() []int64 {
	if x != nil {
		return x.SymGrid
	}
	return nil
}

func (x *Clzw_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Clzw_BetOrderResponse) GetWinArr() []*Clzw_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Clzw_BetOrderResponse) GetStepMul() int64 {
	if x != nil && x.StepMul != nil {
		return *x.StepMul
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetLimit() bool {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return false
}

func (x *Clzw_BetOrderResponse) GetScatterCount() int64 {
	if x != nil && x.ScatterCount != nil {
		return *x.ScatterCount
	}
	return 0
}

func (x *Clzw_BetOrderResponse) GetIsPurchase() bool {
	if x != nil && x.IsPurchase != nil {
		return *x.IsPurchase
	}
	return false
}

func (x *Clzw_BetOrderResponse) GetRoundStep() int64 {
	if x != nil && x.RoundStep != nil {
		return *x.RoundStep
	}
	return 0
}

type Clzw_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *int64                 `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`         // 符号
	SymbolNum     *int64                 `protobuf:"varint,2,opt,name=symbolNum,proto3,oneof" json:"symbolNum,omitempty"`   // 数量
	RoadNum       *int64                 `protobuf:"varint,3,opt,name=roadNum,proto3,oneof" json:"roadNum,omitempty"`       // 中间路数
	Multiplier    *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"` // 倍率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clzw_WinArr) Reset() {
	*x = Clzw_WinArr{}
	mi := &file_clzw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clzw_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clzw_WinArr) ProtoMessage() {}

func (x *Clzw_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_clzw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clzw_WinArr.ProtoReflect.Descriptor instead.
func (*Clzw_WinArr) Descriptor() ([]byte, []int) {
	return file_clzw_proto_rawDescGZIP(), []int{1}
}

func (x *Clzw_WinArr) GetSymbol() int64 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *Clzw_WinArr) GetSymbolNum() int64 {
	if x != nil && x.SymbolNum != nil {
		return *x.SymbolNum
	}
	return 0
}

func (x *Clzw_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Clzw_WinArr) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

var File_clzw_proto protoreflect.FileDescriptor

const file_clzw_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"clzw.proto\x12\x04clzw\"\xd3\b\n" +
	"\x15clzw_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x05 \x01(\x01H\x04R\tbetAmount\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x06 \x01(\x01H\x05R\x06curWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\a \x01(\x01H\x06R\broundWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\b \x01(\x01H\aR\btotalWin\x88\x01\x01\x12'\n" +
	"\ffreeTotalWin\x18\t \x01(\x01H\bR\ffreeTotalWin\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\n" +
	" \x01(\bH\tR\visRoundOver\x88\x01\x01\x12#\n" +
	"\n" +
	"isSpinOver\x18\v \x01(\bH\n" +
	"R\n" +
	"isSpinOver\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\f \x01(\bH\vR\x06isFree\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\r \x01(\x03H\fR\fnewFreeTimes\x88\x01\x01\x123\n" +
	"\x12remainingFreeTimes\x18\x0e \x01(\x03H\rR\x12remainingFreeTimes\x88\x01\x01\x12+\n" +
	"\x0etotalFreeTimes\x18\x0f \x01(\x03H\x0eR\x0etotalFreeTimes\x88\x01\x01\x12\x18\n" +
	"\asymGrid\x18\x10 \x03(\x03R\asymGrid\x12\x18\n" +
	"\awinGrid\x18\x11 \x03(\x03R\awinGrid\x12)\n" +
	"\x06winArr\x18\x12 \x03(\v2\x11.clzw.clzw_WinArrR\x06winArr\x12\x1d\n" +
	"\astepMul\x18\x13 \x01(\x03H\x0fR\astepMul\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x14 \x01(\bH\x10R\x05limit\x88\x01\x01\x12'\n" +
	"\fscatterCount\x18\x15 \x01(\x03H\x11R\fscatterCount\x88\x01\x01\x12#\n" +
	"\n" +
	"isPurchase\x18\x16 \x01(\bH\x12R\n" +
	"isPurchase\x88\x01\x01\x12!\n" +
	"\troundStep\x18\x17 \x01(\x03H\x13R\troundStep\x88\x01\x01B\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\r\n" +
	"\v_multiplierB\f\n" +
	"\n" +
	"_betAmountB\t\n" +
	"\a_curWinB\v\n" +
	"\t_roundWinB\v\n" +
	"\t_totalWinB\x0f\n" +
	"\r_freeTotalWinB\x0e\n" +
	"\f_isRoundOverB\r\n" +
	"\v_isSpinOverB\t\n" +
	"\a_isFreeB\x0f\n" +
	"\r_newFreeTimesB\x15\n" +
	"\x13_remainingFreeTimesB\x11\n" +
	"\x0f_totalFreeTimesB\n" +
	"\n" +
	"\b_stepMulB\b\n" +
	"\x06_limitB\x0f\n" +
	"\r_scatterCountB\r\n" +
	"\v_isPurchaseB\f\n" +
	"\n" +
	"_roundStep\"\xc5\x01\n" +
	"\vclzw_WinArr\x12\x1b\n" +
	"\x06symbol\x18\x01 \x01(\x03H\x00R\x06symbol\x88\x01\x01\x12!\n" +
	"\tsymbolNum\x18\x02 \x01(\x03H\x01R\tsymbolNum\x88\x01\x01\x12\x1d\n" +
	"\aroadNum\x18\x03 \x01(\x03H\x02R\aroadNum\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01B\t\n" +
	"\a_symbolB\f\n" +
	"\n" +
	"_symbolNumB\n" +
	"\n" +
	"\b_roadNumB\r\n" +
	"\v_multiplierB\x19Z\x17egame-grpc/game/clzw/pbb\x06proto3"

var (
	file_clzw_proto_rawDescOnce sync.Once
	file_clzw_proto_rawDescData []byte
)

func file_clzw_proto_rawDescGZIP() []byte {
	file_clzw_proto_rawDescOnce.Do(func() {
		file_clzw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clzw_proto_rawDesc), len(file_clzw_proto_rawDesc)))
	})
	return file_clzw_proto_rawDescData
}

var file_clzw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clzw_proto_goTypes = []any{
	(*Clzw_BetOrderResponse)(nil), // 0: clzw.clzw_BetOrderResponse
	(*Clzw_WinArr)(nil),           // 1: clzw.clzw_WinArr
}
var file_clzw_proto_depIdxs = []int32{
	1, // 0: clzw.clzw_BetOrderResponse.winArr:type_name -> clzw.clzw_WinArr
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clzw_proto_init() }
func file_clzw_proto_init() {
	if File_clzw_proto != nil {
		return
	}
	file_clzw_proto_msgTypes[0].OneofWrappers = []any{}
	file_clzw_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clzw_proto_rawDesc), len(file_clzw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_clzw_proto_goTypes,
		DependencyIndexes: file_clzw_proto_depIdxs,
		MessageInfos:      file_clzw_proto_msgTypes,
	}.Build()
	File_clzw_proto = out.File
	file_clzw_proto_goTypes = nil
	file_clzw_proto_depIdxs = nil
}
