// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/yola1107/kratos/v2"
	"github.com/yola1107/kratos/v2/log"
	"speaker/internal/biz"
	"speaker/internal/conf"
	"speaker/internal/data"
	"speaker/internal/server"
	"speaker/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	engine, cleanup, err := data.NewMysql(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	universalClient := data.NewRedis(confData, logger)
	publisher, cleanup2, err := data.NewRabbitMQ(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(confData, logger, engine, universalClient, publisher)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	speakerRepo := data.NewSpeakerRepo(dataData, logger)
	speakerUsecase := biz.NewSpeakerUsecase(speakerRepo, logger)
	speakerService := service.NewSpeakerService(speakerUsecase)
	grpcServer := server.NewGRPCServer(confServer, speakerService, logger)
	httpServer := server.NewHTTPServer(confServer, speakerService, logger)
	tcpServer := server.NewTCPServer(confServer, speakerService, logger)
	websocketServer := server.NewWebsocketServer(confServer, speakerService, logger)
	gnetServer := server.NewGNETServer(confServer, speakerService, logger)
	app := newApp(logger, grpcServer, httpServer, tcpServer, websocketServer, gnetServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
