// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sbyymx.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sbyymx_BetOrderResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderSN          *string                `protobuf:"bytes,1,opt,name=orderSN,proto3,oneof" json:"orderSN,omitempty"`                     // 订单号
	Balance          *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`                   // 玩家当前余额
	BetAmount        *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`               // 本局下注金额 (baseMoney * multiple * 10)
	CurrentWin       *float64               `protobuf:"fixed64,4,opt,name=currentWin,proto3,oneof" json:"currentWin,omitempty"`             // 本局赢取金额
	TotalWin         *float64               `protobuf:"fixed64,5,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`                 // 本回合总赢取
	Review           *int64                 `protobuf:"varint,6,opt,name=review,proto3,oneof" json:"review,omitempty"`                      // 复盘标志 1=复盘 0=正常
	WinInfo          *Sbyymx_WinInfo        `protobuf:"bytes,7,opt,name=winInfo,proto3,oneof" json:"winInfo,omitempty"`                     // 中奖详情
	Cards            []int64                `protobuf:"varint,8,rep,packed,name=cards,proto3" json:"cards,omitempty"`                       // 符号网格 3x3，按行优先 elements共9个
	IsRoundOver      *bool                  `protobuf:"varint,9,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver,omitempty"`            // 是否本局结束
	WinGrid          []int64                `protobuf:"varint,10,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`                  // 中奖位置网格 3x3
	Next             *bool                  `protobuf:"varint,11,opt,name=next,proto3,oneof" json:"next,omitempty"`                         // 是否需要继续请求（重转至赢）
	IsRespinUntilWin *bool                  `protobuf:"varint,12,opt,name=isRespinUntilWin,proto3,oneof" json:"isRespinUntilWin,omitempty"` // 是否在重转至赢模式中 (有炸胡动画)
	RespinWildCol    *int32                 `protobuf:"varint,13,opt,name=respinWildCol,proto3,oneof" json:"respinWildCol,omitempty"`       // 重转至赢模式长条百搭列 (0-2)，非重转模式为-1
	WildMultiplier   *int64                 `protobuf:"varint,14,opt,name=wildMultiplier,proto3,oneof" json:"wildMultiplier,omitempty"`     // 长条百搭倍数 (x2-x100)
	LineMultiplier   *int64                 `protobuf:"varint,15,opt,name=lineMultiplier,proto3,oneof" json:"lineMultiplier,omitempty"`     // 线赔率合计（各中奖线基础赔率之和，未乘长条百搭）
	StepMultiple     *int64                 `protobuf:"varint,16,opt,name=stepMultiple,proto3,oneof" json:"stepMultiple,omitempty"`         // 本步倍数 (lineMultiplier * wildMultiplier)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Sbyymx_BetOrderResponse) Reset() {
	*x = Sbyymx_BetOrderResponse{}
	mi := &file_sbyymx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sbyymx_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sbyymx_BetOrderResponse) ProtoMessage() {}

func (x *Sbyymx_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sbyymx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sbyymx_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Sbyymx_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_sbyymx_proto_rawDescGZIP(), []int{0}
}

func (x *Sbyymx_BetOrderResponse) GetOrderSN() string {
	if x != nil && x.OrderSN != nil {
		return *x.OrderSN
	}
	return ""
}

func (x *Sbyymx_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil && x.CurrentWin != nil {
		return *x.CurrentWin
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetWinInfo() *Sbyymx_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Sbyymx_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Sbyymx_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Sbyymx_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Sbyymx_BetOrderResponse) GetNext() bool {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return false
}

func (x *Sbyymx_BetOrderResponse) GetIsRespinUntilWin() bool {
	if x != nil && x.IsRespinUntilWin != nil {
		return *x.IsRespinUntilWin
	}
	return false
}

func (x *Sbyymx_BetOrderResponse) GetRespinWildCol() int32 {
	if x != nil && x.RespinWildCol != nil {
		return *x.RespinWildCol
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetWildMultiplier() int64 {
	if x != nil && x.WildMultiplier != nil {
		return *x.WildMultiplier
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetLineMultiplier() int64 {
	if x != nil && x.LineMultiplier != nil {
		return *x.LineMultiplier
	}
	return 0
}

func (x *Sbyymx_BetOrderResponse) GetStepMultiple() int64 {
	if x != nil && x.StepMultiple != nil {
		return *x.StepMultiple
	}
	return 0
}

// sbyymx_WinInfo 中奖详情
type Sbyymx_WinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinArr        []*Sbyymx_WinArr       `protobuf:"bytes,1,rep,name=winArr,proto3" json:"winArr,omitempty"` // 本步各条中奖线的详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sbyymx_WinInfo) Reset() {
	*x = Sbyymx_WinInfo{}
	mi := &file_sbyymx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sbyymx_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sbyymx_WinInfo) ProtoMessage() {}

func (x *Sbyymx_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sbyymx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sbyymx_WinInfo.ProtoReflect.Descriptor instead.
func (*Sbyymx_WinInfo) Descriptor() ([]byte, []int) {
	return file_sbyymx_proto_rawDescGZIP(), []int{1}
}

func (x *Sbyymx_WinInfo) GetWinArr() []*Sbyymx_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

// sbyymx_WinArr 单条中奖线详情
type Sbyymx_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       *int64                 `protobuf:"varint,1,opt,name=roadNum,proto3,oneof" json:"roadNum,omitempty"` // 支付线编号 0
	Odds          *int64                 `protobuf:"varint,2,opt,name=odds,proto3,oneof" json:"odds,omitempty"`       // 基础赔率 来自 pay_table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sbyymx_WinArr) Reset() {
	*x = Sbyymx_WinArr{}
	mi := &file_sbyymx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sbyymx_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sbyymx_WinArr) ProtoMessage() {}

func (x *Sbyymx_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_sbyymx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sbyymx_WinArr.ProtoReflect.Descriptor instead.
func (*Sbyymx_WinArr) Descriptor() ([]byte, []int) {
	return file_sbyymx_proto_rawDescGZIP(), []int{2}
}

func (x *Sbyymx_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Sbyymx_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

var File_sbyymx_proto protoreflect.FileDescriptor

const file_sbyymx_proto_rawDesc = "" +
	"\n" +
	"\fsbyymx.proto\x12\x06sbyymx\"\xb3\x06\n" +
	"\x17sbyymx_BetOrderResponse\x12\x1d\n" +
	"\aorderSN\x18\x01 \x01(\tH\x00R\aorderSN\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01H\x03R\n" +
	"currentWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\x05 \x01(\x01H\x04R\btotalWin\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\x06 \x01(\x03H\x05R\x06review\x88\x01\x01\x125\n" +
	"\awinInfo\x18\a \x01(\v2\x16.sbyymx.sbyymx_WinInfoH\x06R\awinInfo\x88\x01\x01\x12\x14\n" +
	"\x05cards\x18\b \x03(\x03R\x05cards\x12%\n" +
	"\visRoundOver\x18\t \x01(\bH\aR\visRoundOver\x88\x01\x01\x12\x18\n" +
	"\awinGrid\x18\n" +
	" \x03(\x03R\awinGrid\x12\x17\n" +
	"\x04next\x18\v \x01(\bH\bR\x04next\x88\x01\x01\x12/\n" +
	"\x10isRespinUntilWin\x18\f \x01(\bH\tR\x10isRespinUntilWin\x88\x01\x01\x12)\n" +
	"\rrespinWildCol\x18\r \x01(\x05H\n" +
	"R\rrespinWildCol\x88\x01\x01\x12+\n" +
	"\x0ewildMultiplier\x18\x0e \x01(\x03H\vR\x0ewildMultiplier\x88\x01\x01\x12+\n" +
	"\x0elineMultiplier\x18\x0f \x01(\x03H\fR\x0elineMultiplier\x88\x01\x01\x12'\n" +
	"\fstepMultiple\x18\x10 \x01(\x03H\rR\fstepMultiple\x88\x01\x01B\n" +
	"\n" +
	"\b_orderSNB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_currentWinB\v\n" +
	"\t_totalWinB\t\n" +
	"\a_reviewB\n" +
	"\n" +
	"\b_winInfoB\x0e\n" +
	"\f_isRoundOverB\a\n" +
	"\x05_nextB\x13\n" +
	"\x11_isRespinUntilWinB\x10\n" +
	"\x0e_respinWildColB\x11\n" +
	"\x0f_wildMultiplierB\x11\n" +
	"\x0f_lineMultiplierB\x0f\n" +
	"\r_stepMultiple\"?\n" +
	"\x0esbyymx_WinInfo\x12-\n" +
	"\x06winArr\x18\x01 \x03(\v2\x15.sbyymx.sbyymx_WinArrR\x06winArr\"\\\n" +
	"\rsbyymx_WinArr\x12\x1d\n" +
	"\aroadNum\x18\x01 \x01(\x03H\x00R\aroadNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x02 \x01(\x03H\x01R\x04odds\x88\x01\x01B\n" +
	"\n" +
	"\b_roadNumB\a\n" +
	"\x05_oddsB\x1cZ\x1aegame-grpc/game/sbyymx2/pbb\x06proto3"

var (
	file_sbyymx_proto_rawDescOnce sync.Once
	file_sbyymx_proto_rawDescData []byte
)

func file_sbyymx_proto_rawDescGZIP() []byte {
	file_sbyymx_proto_rawDescOnce.Do(func() {
		file_sbyymx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sbyymx_proto_rawDesc), len(file_sbyymx_proto_rawDesc)))
	})
	return file_sbyymx_proto_rawDescData
}

var file_sbyymx_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sbyymx_proto_goTypes = []any{
	(*Sbyymx_BetOrderResponse)(nil), // 0: sbyymx.sbyymx_BetOrderResponse
	(*Sbyymx_WinInfo)(nil),          // 1: sbyymx.sbyymx_WinInfo
	(*Sbyymx_WinArr)(nil),           // 2: sbyymx.sbyymx_WinArr
}
var file_sbyymx_proto_depIdxs = []int32{
	1, // 0: sbyymx.sbyymx_BetOrderResponse.winInfo:type_name -> sbyymx.sbyymx_WinInfo
	2, // 1: sbyymx.sbyymx_WinInfo.winArr:type_name -> sbyymx.sbyymx_WinArr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sbyymx_proto_init() }
func file_sbyymx_proto_init() {
	if File_sbyymx_proto != nil {
		return
	}
	file_sbyymx_proto_msgTypes[0].OneofWrappers = []any{}
	file_sbyymx_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sbyymx_proto_rawDesc), len(file_sbyymx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sbyymx_proto_goTypes,
		DependencyIndexes: file_sbyymx_proto_depIdxs,
		MessageInfos:      file_sbyymx_proto_msgTypes,
	}.Build()
	File_sbyymx_proto = out.File
	file_sbyymx_proto_goTypes = nil
	file_sbyymx_proto_depIdxs = nil
}
